DBLATEX_STYLE ?= db2latex
DBLATEX_BACKEND ?= pdftex

%.pdf:
	if [ -e $*.xml ]; then \
		dblatex --backend=$(DBLATEX_BACKEND) \
		--style=$(DBLATEX_STYLE) \
		--param=section.label.includes.component.label=1 \
		--output=$@ $*.xml; \
	elif [ -e $*.svg ]; then \
		rsvg-convert -f pdf -o $@ $*.svg; \
	fi

clean-pdf:
	rm -f $(XML_FILES:.xml=.pdf)
	rm -f $(SVG_FILES:.svg=.pdf)
