[[about]]
[preface]
== はじめにお読みください

本書はDistributed Replicated Block Device
(DRBD)を利用するための完全なリファレンスガイドです。同時にハンドブックとしても活用できるように編集してあります。

本書はDRBDプロジェクトのスポンサーである http://www.linbit.com/[LINBIT]
がそのコミュニティ向けに作成しています。そしてコミュニティにとって有益であることを願って無償で公開しています。本書はDRBDのリリースに合わせて継続的に更新しています。DRBDの新しいリリースと同時に、その新機能の説明を追加する予定です。オンラインHTML版は
http://www.drbd.org/users-guide/ で公開しています。

IMPORTANT: このガイドはDRBD 8.4.0以降をご使用のユーザを対象にしています。DRBD 8.4より前のバージョンを使用する場合は、旧版のガイド
http://www.drbd.org/users-guide-8.3/ をご利用ください。

本書に対する改善提案や誤りの指摘は <<s-mailing-list, DRBD関連メーリングリスト>> へお寄せください。

本書は次の構成になっています。

* <<p-intro>>
  ではDRBDの基本的な機能を扱います。LinuxのI/OスタックにおけるDRBDの位置付け、DRBDの基本コンセプトなど、基礎となる事項を取り扱います。また、DRBDのもっとも重要な機能について検討を加えます。

* <<p-build-install-configure>>
  ではソースからのDRBDのビルド方法、コンパイル済みのパッケージからのインストール方法、またクラスタシステムでのDRBDの運用方法の概要について説明します。

* <<p-work>> ではDRBDの管理方法、DRBDリソースの設定や修正方法、一般的なトラブルシューティングを説明します。

* <<p-apps>>
  ではストレージのレプリケーションの追加やアプリケーションの高可用性のためDRBDを活用する方法を説明します。Pacemakerクラスタ管理システムとの組み合わせだけでなく、LVMとの高度な組み合わせ、GFSとの組み合わせ、Xenによる仮想環境の可用性向上についても触れます。

* <<p-performance>> ではDRBD設定によりパフォーマンスを向上させるための方法について説明します。

* <<p-learn>> ではDRBDの内部構造を説明します。読者に有益と思われる他の情報リソースについても紹介します。

* <<p-appendices>>: ** <<ap-recent-changes>> は DRBD の以前のリリースと比較した DRBD 8.4
  の変更点の概要です。

DRBDトレーニングやサポートサービスにご興味のある方は sales@3ware.co.jp にお問い合せください。
