[[ch-benchmark]]
== ブロックデバイスのパフォーマンス測定

[[s-measure-throughput]]
=== スループットの測定

DRBDを使用することによるシステムのI/Oスループットへの影響を測定する際には、スループットの絶対値はほとんど意味がありません。必要なのは、DRBDがI/Oパフォーマンスに及ぼす相対的な影響です。したがって、I/Oスループットを測定する際には、必ずDRBDがある場合とない場合の両方を測定する必要があります。

CAUTION: ここで説明するテストは破壊的です。データが上書きされるため、DRBDデバイスの同期が失われます。したがって、テストが完了したら破棄することができるスクラッチボリュームに対してのみテストを行ってください。

I/Oスループットを見積もるには、比較的大きなデータチャンクをブロックデバイスに書き込み、システムが書き込み操作を完了するまでの時間を測定します。これは一般的なユーティリティ
`dd` を使用して簡単に測定できます。比較的新しいバージョンにはスループット見積もり機能が組み込まれています。

簡単な `dd` ベースのスループットベンチマークは、たとえば次のようになります。ここでは、 `test`
という名前のスクラッチリソースが現在接続されており、両方のノードでセカンダリロールになっています。

[source, drbd]
----------------------------
# TEST_RESOURCE=test
# TEST_DEVICE=$(drbdadm sh-dev $TEST_RESOURCE)
# TEST_LL_DEVICE=$(drbdadm sh-ll-dev $TEST_RESOURCE)
# drbdadm primary $TEST_RESOURCE
# for i in $(seq 5); do
    dd if=/dev/zero of=$TEST_DEVICE bs=512M count=1 oflag=direct
  done
# drbdadm down $TEST_RESOURCE
# for i in $(seq 5); do
    dd if=/dev/zero of=$TEST_LL_DEVICE bs=512M count=1 oflag=direct
  done
----------------------------

このテストでは、512MのデータチャンクをDRBDデバイスに書き込み、次に比較のために下位デバイスに書き込みます。両方のテストをそれぞれ5回繰り返し、統計平均を求めます。結果は
`dd` が生成するスループット測定です。

NOTE: 新規に有効にしたDRBDデバイスの場合は、最初の `dd`
実行ではパフォーマンスがかなり低くなりますが、これは正常な状態です。アクティビティログがいわゆる「コールド」な状態のためで、問題はありません。

[[s-measure-latency]]
=== 待ち時間の測定

待ち時間を測定する際の対象はスループットベンチマークとはまったく異なります。I/O待ち時間テストでは、非常に小さいデータチャンク(理想的にはシステムが処理可能な最も小さいデータチャンク)を書き込み、書き込みが完了するまでの時間を測定します。通常はこれを何度か繰り返して、通常の統計変動を相殺します。

スループットの測定と同様に、I/O待ち時間の測定にも一般的な `dd` ユーティリティを使用できますが、異なる設定とまったく異なった測定を行います。

以下は簡単な `dd` ベースの待ち時間のマイクロベンチマークです。ここでは、 `test`
という名前のスクラッチリソースが現在接続されており、両方のノードでセカンダリロールになっています。

[source, drbd]
----------------------------
# TEST_RESOURCE=test
# TEST_DEVICE=$(drbdadm sh-dev $TEST_RESOURCE)
# TEST_LL_DEVICE=$(drbdadm sh-ll-dev $TEST_RESOURCE)
# drbdadm primary $TEST_RESOURCE
# dd if=/dev/zero of=$TEST_DEVICE bs=512 count=1000 oflag=direct
# drbdadm down $TEST_RESOURCE
# dd if=/dev/zero of=$TEST_LL_DEVICE bs=512 count=1000 oflag=direct
----------------------------

このテストでは、512バイトのデータチャンクをDRBDデバイスに1,000回書き込み、次に比較のために下位デバイスにも1000回書き込みます。512バイトはLinuxシステム(s390以外のすべてのアーキテクチャ)が扱うことができる最小のブロックサイズです。

`dd`
が生成するスループット測定はこのテストではまったく意味がなく、ここで重要なのは、1,000回の書き込みが完了するまでにかかった時間です。この時間を1,000で割ると、1つのセクタへの書き込みの平均待ち時間を求めることができます。
