[[ch-install-packages]]
== コンパイル済みDRBDバイナリパッケージのインストール


[[s-linbit-packages]]
=== LINBIT社が提供するパッケージ

DRBDプロジェクトのスポンサー企業であるLINBIT社は、商用サポート対象のお客様向けにDRBDバイナリパッケージを提供しています。これらパッケージは
http://www.linbit.com/support/ から入手可能であり、「公式DRBDビルド」です。

これらのビルドは次のディストリビューションで入手できます。

* Red Hat Enterprise Linux (RHEL)バージョン5、6、7

* SUSE Linux Enterprise Server (SLES)バージョン11SP4、12

* Debian GNU/Linux, 8 (jessie)、9 (stretch)

* Ubuntu Server Edition LTS 14.04 (Trusty Tahr)、16.04 (Xenial Xerus)、LTS 18.04
  (Bionic Beaver)

LINBIT社では、新規のDRBDソースのリリースと並行してバイナリビルドをリリースしています。

RPMベースのシステム(SLES、RHEL)へのパッケージのインストールはパッケージ名とともに `rpm -i` (新規インストールの場合)または
`rpm -U` (アップグレードの場合)コマンドを呼び出すことで簡単に行えます。

Debianベースのシステム(Debian GNU/Linux、Ubuntu)では、 `drbd8-utils` と `drbd8-module`
パッケージを `dpkg -i` または `gdebi` コマンドでインストールします(該当する場合)。


[[s-distro-packages]]
=== ディストリビューションベンダが提供するパッケージ

コンパイル済みバイナリパッケージを含め、いくつかのディストリビューションでDRBDが配布されています。これらのパッケージに対するサポートは、それぞれのディストリビュータが提供します。リリースサイクルは、DRBDソースのリリースより遅れる場合があります。

[[s-suse_linux_enterprise_server]]
==== SUSE Linux Enterprise Server

SUSE Linux Enterprise Server (SLES)バージョン9、10にはDRBD 0.7が含まれ、SLES 11 High
Availability Extension (HAE) SP1 にはDRBD 8.3が含まれます。

SLESの場合、DRBDは通常はYaST2のソフトウェアインストールコンポーネントによりインストールされます。これは High
Availabilityパッケージセレクションに同梱されています。

コマンドラインを使用してインストールする場合は、次のコマンドを実行します。

---------------------------------------
yast -i drbd
---------------------------------------

または

---------------------------------------
zypper install drbd
---------------------------------------


[[s-_debian_gnu_linux]]
====  Debian GNU/Linux

Debian GNU/Linuxリリース5.0 ( `lenny` )以降にDRBD 8が含まれ、Linuxカーネル2.6.32である6.0 (
`squeeze` )では、Debianには移植バージョンのDRBDが提供されています。

DRBDがストックカーネルに含まれているため、 `squeeze` で必要なのは `drbd8-utils` パッケージのインストールのみです。

---------------------------------------
apt-get install drbd8-utils
---------------------------------------

`lenny` (obsolete)では、次のようにしてDRBDをインストールします。

---------------------------------------
apt-get install drbd8-utils drbd8-module
---------------------------------------

[[s-centos]]
==== CentOS

CentOSのリリース5からDRBD 8が含まれています。

DRBDは `yum` コマンドでインストールできます( `extras` リポジトリ (または EPEL / ELRepo)
が有効になっている事が必要な事に注意してください)。

---------------------------------------
yum install drbd kmod-drbd
---------------------------------------


[[s-ubuntu_linux]]
==== Ubuntu Linux

UbuntuにDRBDをインストールするには次のコマンドを実行します。

---------------------------------------
apt-get update
apt-get install drbd8-utils
---------------------------------------

古いUbuntuのバージョンでは、 `drbd8-module`
も明示的にインストールする必要があります。新しいバージョンではデフォルトのカーネルにすでにアップストリームのDRBDバージョンが含まれています。

[[s-from-source]]
=== ソースからパッケージをコンパイル

https://github.com/LINBIT[github] のgit
tagsで生成されたリリースは、特定の時刻のgitリポジトリのスナップショットであり、マニュアルページ、 `configure`
スクリプト、他の生成ファイル不足などで使用したくないかもしれません。tarballからビルドする場合は、
https://www.linbit.com/en/drbd-community/drbd-download/ を使用してください。

すべてのプロジェクトには、標準のビルドスクリプト（ `Makefile` 、 `configure`
）が含まれています。ディストリビューションごとに特定の情報を維持することは手間がかかり、歴史的にこれらの情報はすぐに古くになっています。標準的な方法でソフトウェアをビルドする方法がわからない場合は、LINBITが提供するパッケージの使用を検討してください。
