[[ch-install-packages]]
== コンパイル済みDRBDバイナリパッケージのインストール


[[s-linbit-packages]]
=== LINBIT社が提供するパッケージ

DRBDプロジェクトのスポンサー企業であるLINBIT社は、商用サポート対象のお客様向けにDRBDバイナリパッケージを提供しています。これらパッケージは
http://www.linbit.com/support/ から入手可能であり、「公式DRBDビルド」です。

これらのビルドは次のディストリビューションで入手できます。

* Red Hat Enterprise Linux (RHEL)バージョン5、6、7

* SUSE Linux Enterprise Server (SLES)バージョン10、11、12 (サービスパックを含む)

* Debian GNU/Linux バージョン5 (lenny)、6 (squeeze)、7 (wheezy)、8 (jessie)

* Ubuntu Server Edition LTS バージョン, 12.04 (precise), 14.04 (trusty), 16.04
  (xenial)

LINBIT社では、新規のDRBDソースのリリースと並行してバイナリビルドをリリースしています。

RPMベースのシステム(SLES、RHEL)へのパッケージのインストールはパッケージ名とともに `rpm -i` (新規インストールの場合)または
`rpm -U` (アップグレードの場合)コマンドを呼び出すことで簡単に行えます。

Debianベースのシステム(Debian GNU/Linux、Ubuntu)では、 `drbd8-utils` と `drbd8-module`
パッケージを `dpkg -i` または `gdebi` コマンドでインストールします(該当する場合)。


[[s-distro-packages]]
=== ディストリビューションベンダが提供するパッケージ

コンパイル済みバイナリパッケージを含め、いくつかのディストリビューションでDRBDが配布されています。これらのパッケージに対するサポートは、それぞれのディストリビュータが提供します。リリースサイクルは、DRBDソースのリリースより遅れる場合があります。

==== SUSE Linux Enterprise Server

SUSE Linux Enterprise Server (SLES)バージョン9、10にはDRBD 0.7が含まれ、SLES 11 High
Availability Extension (HAE) SP1 にはDRBD 8.3が含まれます。

SLESの場合、DRBDは通常はYaST2のソフトウェアインストールコンポーネントによりインストールされます。これは High
Availabilityパッケージセレクションに同梱されています。

コマンドラインを使用してインストールする場合は、次のコマンドを実行します。

---------------------------------------
yast -i drbd
---------------------------------------

または

---------------------------------------
zypper install drbd
---------------------------------------


====  Debian GNU/Linux

Debian GNU/Linuxリリース5.0 ( `lenny` )以降にDRBD 8が含まれ、Linuxカーネル2.6.32である6.0 (
`squeeze` )では、Debianには移植バージョンのDRBDが提供されています。

DRBDがストックカーネルに含まれているため、 `squeeze` で必要なのは `drbd8-utils` パッケージのインストールのみです。

---------------------------------------
apt-get install drbd8-utils
---------------------------------------

`lenny` (obsolete)では、次のようにしてDRBDをインストールします。

---------------------------------------
apt-get install drbd8-utils drbd8-module
---------------------------------------

==== CentOS

CentOSのリリース5からDRBD 8が含まれています。

DRBDは `yum` コマンドでインストールできます( `extras` リポジトリ (または EPEL / ELRepo)
が有効になっている事が必要な事に注意してください)。

---------------------------------------
yum install drbd kmod-drbd
---------------------------------------


==== Ubuntu Linux

UbuntuにDRBDをインストールするには次のコマンドを実行します。

---------------------------------------
apt-get update
apt-get install drbd8-utils
---------------------------------------

On (very) old Ubuntu versions you might need to explicitly install
`drbd8-module`, too; in newer versions the default kernel already includes
the upstream DRBD version.
