[[ch-more-info]]
== 詳細情報の入手

[[s-commercial-support]]
=== 商用DRBDのサポート

DRBDの商用サポート、コンサルティング、トレーニングサービスは、プロジェクトのスポンサ企業LINBIT社が提供しています。日本では
http://www.linbit.com/[LINBIT] 社との提携にもとづいて株式会社サードウェアが各種サポートを提供しています。

[[s-mailing-list]]
=== 公開メーリングリスト

DRBDの一般的な使用法について質問がある場合は、公開メーリングリスト drbd-user@lists.linbit.com
にお問い合せください。このメーリングリストは登録が必要です。 http://lists.linbit.com/drbd-user
で登録してください。すべてのアーカイブのリストは http://lists.linbit.com/pipermail/drbd-user にあります。

[[s-irc-channels]]
=== 公開IRCチャンネル

公開IRCサーバ `irc.freenode.net` の次のチャンネルに、DRBDの開発者も参加しています。

* `#drbd`,
* `#linux-ha`,
* `#linux-cluster`.

IRCを使って、DRBDの改善を提案したり、開発者レベルの議論をするときもあります。

[[s-twitter-account]]
=== 公開ツイッターアカウント

http://www.linbit.com/[LINBIT] は公開 http://twitter.com/linbit[twitter
account] をメンテナンスしています。

DRBDについてツイートする際は、 `#drbd` ハッシュタグをつけてください。

[[s-publications]]
=== 資料

DRBDの開発者により作成されたDRBD一般やDRBDの特定の機能についての文書が公開されています。その一部を次に示します。

[bibliography]
- Lars Ellenberg. 'DRBD v8.0.x and beyond'. 2007. Available at
  http://www.drbd.org/fileadmin/drbd/publications/drbd8.linux-conf.eu.2007.pdf
- Philipp Reisner. 'DRBD v8 - Replicated Storage with Shared Disk
  Semantics'. 2007. Available at
  http://www.drbd.org/fileadmin/drbd/publications/drbd8.pdf.
- Philipp Reisner. 'Rapid resynchronization for replicated
  storage'. 2006. Available at
  http://www.drbd.org/fileadmin/drbd/publications/drbd-activity-logging_v6.pdf

[[s-useful-resources]]
=== その他の資料

* Wikipedaにはhttp://en.wikipedia.org/wiki/DRBD[an entry on DRBD]があります。
* http://wiki.linux-ha.org/[Linux-HA wiki]と
* http://www.clusterlabs.org[ClusterLabs]に、高可用性クラスタでDRBDを活用するための有益な情報があります。
