[[ch-install-packages]]
== Installing pre-built DRBD binary packages


[[s-linbit-packages]]
=== Packages supplied by LINBIT

LINBIT, the DRBD project's sponsor company, provides DRBD binary
packages to its commercial support customers. These packages are
available at http://www.linbit.com/support/ and are considered
"official" DRBD builds.

These builds are available for the following distributions:

* Red Hat Enterprise Linux (RHEL), versions 5, 6, and 7

* SUSE Linux Enterprise Server (SLES), versions 11SP4, and 12

* Debian GNU/Linux, 8 (jessie), and 9 (stretch)

* Ubuntu Server Edition LTS 16.04 (Xenial Xerus), and LTS 18.04 (Bionic Beaver).

LINBIT releases binary builds in parallel with any new DRBD source
release.

Package installation on RPM-based systems (SLES, RHEL) is done by
simply invoking `rpm -i` (for new installations) or `rpm -U` (for
upgrades), along with the corresponding package names.

For Debian-based systems (Debian GNU/Linux, Ubuntu) systems,
`drbd8-utils` and `drbd8-module` packages are installed with `dpkg -i`,
or `gdebi` if available.


[[s-distro-packages]]
=== Packages supplied by distribution vendors

A number of distributions include DRBD, including pre-built binary
packages. Support for these builds, if any, is being provided by the
associated distribution vendor. Their release cycle may lag behind
DRBD source releases.

[[s-suse_linux_enterprise_server]]
==== SUSE Linux Enterprise Server

SUSE Linux Enterprise Server (SLES), includes DRBD 0.7 in versions 9
and 10. DRBD 8.3 is included in SLES 11 High Availability Extension
(HAE) SP1.

On SLES, DRBD is normally installed via the software installation
component of YaST2. It comes bundled with the High Availability
package selection.

Users who prefer a command line install may simply issue:

---------------------------------------
yast -i drbd
---------------------------------------

or

---------------------------------------
zypper install drbd
---------------------------------------


[[s-_debian_gnu_linux]]
====  Debian GNU/Linux

Debian GNU/Linux includes DRBD 8 from the 5.0 release (`lenny`)
onwards. In 6.0 (`squeeze`), which is based on a 2.6.32 Linux kernel,
Debian ships a backported version of DRBD.

On `squeeze`, since DRBD is already included with the stock kernel,
all that is needed to install is the `drbd8-utils` package:

---------------------------------------
apt-get install drbd8-utils
---------------------------------------

On `lenny` (obsolete), you install DRBD by issuing:

---------------------------------------
apt-get install drbd8-utils drbd8-module
---------------------------------------

[[s-centos]]
==== CentOS

CentOS has had DRBD 8 since release 5.

DRBD can be installed using `yum` (note that you will need the
`extras` repository (or EPEL / ELRepo) enabled for this to work):

---------------------------------------
yum install drbd kmod-drbd
---------------------------------------


[[s-ubuntu_linux]]
==== Ubuntu Linux

To install DRBD on Ubuntu, you issue these commands:

---------------------------------------
apt-get update
apt-get install drbd8-utils
---------------------------------------

On (very) old Ubuntu versions you might need to explicitly install
`drbd8-module`, too; in newer versions the default kernel already includes the
upstream DRBD version.

[[s-from-source]]
=== Compiling packages from source

Releases generated by git tags on https://github.com/LINBIT[github] are snapshots of the git repository at the
given time. You most likely do not want to use these. They might lack things such as generated man pages, the
`configure` script, and other generated files. If you want to build from a tarball, use the ones
https://www.linbit.com/en/drbd-community/drbd-download[provided by us].

All our projects contain standard build scripts (e.g., `Makefile`, `configure`). Maintaining specific
information per distribution (e.g., documenting broken build macros) is too cumbersome, and historically the
information provided in this section got outdated quickly. If you don't know how to build software the
standard way, please consider using packages provided by LINBIT.
