[[about]]
[preface]
== はじめにお読みください

本書はDistributed Replicated Block Device
(DRBD)を利用するための完全なリファレンスガイドです。同時にハンドブックとしても活用できるように編集してあります。

本書はDRBDプロジェクトのスポンサーである http://www.linbit.com/[LINBIT]
がそのコミュニティ向けに作成しています。そしてコミュニティにとって有益であることを願って無償で公開しています。本ユーザーズガイドは、随時更新しています。DRBDの新しいリリースと同時に、その新機能の説明を追加する予定です。オンラインHTML版は
https://links.linbit.com/DRBD9-Users-Guide で公開しています。

IMPORTANT: このガイドはDRBDの最新バージョンのユーザーを対象にしています。DRBDバージョン8.4をご使用の場合には
https://links.linbit.com/DRBD84-Users-Guide から対応するバージョンをご利用ください。

本書に対する改善提案や誤りの指摘は<<s-mailing-list,the drbd-user mailing list>>へお寄せください。

本書は次の構成になっています。

* <<p-intro>>ではDRBDの基本的な機能を扱います。Linuxの
  I/OスタックにおけるDRBDの位置付け、DRBDの基本コンセプトなど、基礎となる事項を取り扱います。また、DRBDのもっとも重要な機能について説明します。

* <<p-build-install-configure>>
  ではDRBDのビルド方法、コンパイル済みのパッケージからのインストール方法、またクラスタシステムでのDRBDの運用方法の概要について説明します。

* <<p-work>>ではDRBDの管理方法、DRBDリソースの設定や修正方法、一般的なトラブルシューティングを説明します。

* <<p-apps>>ではストレージのレプリケーションの追加やアプリケーションの高可用性のためDRBDを活用する方法を説明します。ここではDRBDとPacemakerクラスタ管理システムとの組み合わせだけでなく、LVMとの高度な組み合わせ、GFSとの組み合わせ、Xenによる仮想環境の可用性向上についても触れます。

* <<p-performance>>ではパフォーマンスを向上させるDRBDの設定について説明します。

* <<p-learn>> ではDRBDの内部構造を説明します。読者に有益と思われる他の情報リソースについても紹介します。

* <<p-appendices>>: ** <<ap-recent-changes>>はこれまでのDRBDバージョンと
    比較した、DRBD9.0での変更点の概要です。

DRBDトレーニングやサポートサービスにご興味のある方は sales@linbit.com または sales_us@linbit.com
にお問い合せください。
