LINSTORはDRBDのSDSスタックを扱う上でとてもパワフルな構成要素です。ただ、今のところオプション扱いです。手動でリソースを扱う場合は、<<ch-admin-manual>>
を参照ください。

[[s-common_administration]]
== 共通の管理

LINSTORはLinuxシステムのストレージの構成管理システムです。クラスターノードのLVM論理ボリュームとZFS
ZVOLを管理します。異なるノード間の複製にDRBDを利用し、ユーザとアプリケーションにブロックストレージデバイスを供給します。LINSTORはスナップショット、暗号化、bcacheを通してSSDのHDDバックアップデータのキャッシュを管理します。

この章では日々のオペレーションで起きる典型的な管理作業を説明します。トラブル対策に関しては、<<ch-troubleshooting>>
を参照ください。

[[s-concepts_and_terms]]
=== 概念と用語

LINSTORのセットアップには１つのアクティブコントローラと複数のサテライトがあります。_linstor-controller_
はクラスタ全体のすべての構成情報を含むデーターベースをもちます。コントローラはシステムの重要な部分であるので、通常PacemakerとDRBDを使ってHAサービスとして構成されます。

_linstor-satellite_
はローカルストレージを供給する、または、ストレージをサービスとして供給するすべてのノードで実行され、必要なすべての情報をコントローラから受け取ります。`lvcreate`
や `drbdadm` がそこで実行され、ノードエージェントのように振る舞います。

_linstor-client_ はコマンドラインのユーティリティで、システムにコマンドを発行したり、ステータスを取得したりします。

[[s-broader_context]]
=== よりハイレベルな適用

LINSTORはDRBD管理をより便利にするものとして使われる一方で、よりハイレベルなソフトウェアスタックとしても使われます。例えば、Kubernetes、OpenStack、OpenNebula、Proxmoxなどが該当します。

LINSTORのサウスバウンドドライバには、LVM、thinLVM、ZFSがあり、Swordfishのサポートも現在開発中です。

[[s-packages]]
=== パッケージ

LINSTORはRPMとDEB形式でパッケージングされています。

. _linstor-client_
  にはコマンドラインのクライアントプログラムが含まれていて、通常すでにインストールされているpythonのみに依存しています。
. _linstor-controller_ には _controller_ が、_linstor-controller_ には _satellite_
  が含まれています。これらのサービスのためのsystemd関連ファイルも含みます。Java実行環境(JRE)のバージョン1.8以上に依存していて、依存関係で約100MB必要になります。

[[s-linstor-init-cluster]]
=== クラスタの初期化
以下の手順がすべてのクラスタノードですでに実行されていると仮定します。

. DRBD9カーネルモジュールがインストール、ロードされている。
. `drbd-utils` がインストールされている。
. `LVM` ツールがインストールされている。
. `linstor-controller`, `linstor-satellite` とその依存パッケージがインストールされている。

linstor-controllerサービスを起動します。

----------------------------
# systemctl start linstor-controller
----------------------------

[[s-linstor-migrate-from-dm]]
=== DRBDManageからリソースの移行
LINSTORクライアントには既存のDRBDManageノードとリソースをLINSTORに加える移行スクリプトを生成できるサブコマンドがあります。移行は中断なしで実行できます。既存のリソースの移行が不要な場合は、次のセクションに移動してください。

まず最初にDRBDManageの状態が正常かどうか確認します。`drbdmanage assignments`
出力が問題なければ、`drbdmanage export-ctrlvol > ctrlvol.json`
で、LINSTORクライアントの入力として使える既存のクラスタデータベースを抽出できます。クライアントはすぐに移行を実行するわけではなく、単にシェルスクリプトを生成します。よって、移行アシスタントを何回も実行したり、生成されたスクリプトを実際に実行する前にチェックし、変更することもできます。移行スクリプトの生成は、`linstor
dm-migrate ctrlvol.json dmmmigrate.sh`
で行います。スクリプトはいくつか質問した後にシェルスクリプトを生成します。スクリプトを注意深く読んだ後に、DRBDManageを止めて以下のファイル名を変更します。ファイル名を変更しないと、下位のdrbd-utilsがDRBDManageとLINSTORの両方のリソースファイルから取得してしまいます。

１つのノードでlinstor-controllerサービスをスタートさせる、すべてのノードでlinstor-satelliteサービスをスタートさせるのを忘れないでください。

----------------------------
# drbdmanage shutdown -qc # すべてのノードで
# mv /etc/drbd.d/drbdctrl.res{,.dis} # すべてのノードで
# mv /etc/drbd.d/drbdmanage-resources.res{,.dis} # すべてのノードで
# bash dmmigrate.sh
----------------------------

[[s-using_the_linstor_client]]
=== LINSTORクライアントの使用
LINSTORコマンドラインクライアントを実行するときは、常にlinstor-controllerがどこで実行されているか知る必要があります。何も指定してないときは、IP
`127.0.0.1` port `3376` のローカルのlinstor-controllerを探しにいきます。

----------------------------
# linstor node list
----------------------------
これは空のノードリストをエラーメッセージなしで表示します。

`linstor`
コマンドはどのマシンでも実行できます。ただし、クライアントにどのようにlinstor-controllerを探すか指定する必要があります。これはコマンドラインのオプションか、環境変数、またはグローバルファイルで指定できます。

----------------------------
# linstor --controllers=alice node list
# LS_CONTROLLERS=alice linstor node list
# cat /etc/linstor/linstor-client.conf
[global]
controllers=alice
----------------------------
FIXME describe how to specify multiple controllers

[[s-adding_nodes_to_your_cluster]]
=== ノードをクラスタに追加する
次の手順ではノードをクラスタに追加します。

. ノード名は `uname -n` の出力と同じである必要がある。
. ノードのIPアドレスとともに以下を実行する。

----------------------------
# linstor node create bravo 10.43.70.3
----------------------------

`linstor node list`
を実行したとき、新しいノードはofflineとマークされています。ここで、以下のコマンドでlinstor-satelliteを起動します。
----------------------------
# systemctl start linstor-satellite
----------------------------
10秒後に `linstor node list`
がonlineになるのを見るでしょう。もちろんコントローラが認識する前にlinstor-satelliteがすでに起動されているときもあります。

NOTE: ノードがコントローラでかつクラスタにストレージも供給する場合は、同様にlinstor-satelliteを起動します。

[[s-storage_pools]]
=== ストレージプール

ストレージプールはLINSTORでストレージを識別します。複数のノードからのストレージプールをグループ化するために単純に各ノードで同じ名前を使います。例えば１つの有効な方法としてすべてのSSDに１つの名前をつけ、すべてのHDDに別の名前をつけます。

ストレージを作成するために、LVM VGまたはZFS
zPoolのどちらかを作成する必要があります。LINSTORストレージプール名とともに識別されるVGsやzPools名は、各ホストで別の名前にすることも可能ですが、すべてのノードで同じにすることを推奨します。

----------------------------
# vgcreate vg_ssd /dev/nvme0n1 /dev/nvme1n1 [...]
----------------------------

次にこれらは以下のコマンドでLINSTORに登録します。

----------------------------
# linstor storage-pool create lvm alpha pool_ssd vg_ssd
# linstor storage-pool create lvm bravo pool_ssd vg_ssd
----------------------------

NOTE: ストレージプール名は _ストレージプール定義_ として参照されます。上記コマンドはストレージプール定義を暗黙的に作成します。 `linstor
storage-pool-definition list`
を使って確認できます。明示的にストレージプール定義を作成することも可能ですが、必須ではありません。

[[s-a_storage_pool_per_backend_device]]
==== 下位デバイスごとのストレージプール

クラスタ内にホット修復機能を備えたストレージしか持たないクラスタでは、物理的な下位デバイスごとに1つのストレージプールを作成するモデルを選択のもよいかもしれません。このモデルの利点は、障害ドメインを単一のストレージデバイスに限定することです。


[[s-linstor-set-config]]
=== クラスタ構成
FIXME

[[s-available_storage_plugins]]
==== 利用可能なストレージプラグイン

indexterm:[linstor, storage plugins]

LINSTORは現時点で以下の３つのストレージプラグインをサポートしています。

  * Thick LVM

  * 単一の thin プールの Thin LVM

  * ZFS

FIXME

[[s-linstor-new-volume]]

=== リソース、ボリュームの作成と配備
以下の例では、500 GBのサイズをもつリソースを作成し、３つのクラスタノード間で複製されるというシナリオを紹介します。

最初に新しいリソースの定義を作成します。

----------------------------
# linstor resource-definition create backups
----------------------------

次にこのリソースをもつ新しいボリュームの定義を作成します。

----------------------------
# linstor volume-definition create backups 500G
----------------------------

ここまではLINSTORのデータベースにオブジェクトが作成されただけで、ストレージノードのLVには作成されていません。この後はLINSTORに配備作業を委任するか自分でやるか選択できます。

[[s-manual_placement]]
==== 手動配備

`resource create` コマンドでリソース定義を指定したノードに明示的に割り当てることができます。

----------------------------
# linstor resource create alpha backups --storage-pool pool_hdd
# linstor resource create bravo backups --storage-pool pool_hdd
# linstor resource create charlie backups --storage-pool pool_hdd
----------------------------

[[s-autoplace-linstor]]
==== 自動配備

オプション--auto-placeに続く数値は複製の数を指定します。--storage-poolはストレージプール名を指定します。
----------------------------
# linstor resource create backups --auto-place 3 --storage-pool pool_hdd
----------------------------
ストレージプール名がはっきりしない場合、`--storage-pool`
を省略できます。この場合、LINSTORが以下のルールに基づいてストレージプールを選択します。

  * 現在のユーザがアクセスできないすべてのノードとストレージプールは無視する。
  * すべてのディスクのないストレージプールは無視する
  * 十分な空き領域がないストレージプールは無視する

残ったストレージプールから、LINSTORが最も空き領域があるものを選択します。

[[s-drbd_clients]]
==== DRBDクライアント
`--storage-pool` オプションに代わって `--diskless`
オプションを使うことでノードに永続的なディスクレスDRBDデバイスを作成できます。

----------------------------
# linstor resource create delta backups --diskless
----------------------------

[[s-volumes_of_one_resource_to_different_storage_pools]]
==== 1つのリソースから異なるストレージプールへのボリューム
リソースをノードに配備する前のボリューム定義で `StorPoolName`
プロパティを使うことで、1つのリソースから異なるストレージプールへのボリュームを作成できます。

----------------------------
# linstor resource-definition create backups
# linstor volume-definition create backups 500G
# linstor volume-definition create backups 100G
# linstor volume-definition set-property backups 0 StorPoolName pool_hdd
# linstor volume-definition set-property backups 1 StorPoolName pool_ssd
# linstor resource create alpha backups
# linstor resource create bravo backups
# linstor resource create charlie backups
----------------------------

NOTE: `volume-definition create` コマンドが `--vlmnr`
なしで使用されたので、LINSTORはボリューム番号を0から割り当てました。続く２行で指定されている、0, 1
の数値はこれら自動的に割り当てられたボリューム番号を示します。

ここでの 'resource create' は`--storage-pool`
オプションを必要としません。この場合LINSTORはストレージプールのフォールバックを使用します。LINSTORは以下のオブジェクトに対してこの順番で問い合わせを行います。

  * ボリューム定義
  * リソース
  * リソース定義
  * ノード

どのオブジェクトも `StorPoolName` プロパティを含んでいない場合、コントローラはストレージプールとして 'DfltStorPool'
という文字列にフォールバックします。

これはまた、ストレージプール名を忘れてしまって、LINSTORが 'DfltStorPool'
というストレージプールを見つけられなかった場合は、エラーが表示されるということを意味します。

[[s-managing_network_interface_cards]]
=== ネットワークインターフェイスカードの管理

LINSTORはマシンの複数のネットワークインターフェイスカード(NIC)を扱えます。LINSTORでこれらは `netif` と呼びます。

NOTE: サテライトノードが作成されると最初の `netif` が `default` という名前で暗黙に作られます。`node create` コマンドで
`--interface-name` オプションを指定することにより、別の名前を与えることができます。

追加のNICは以下のようにして作られます。
----------------------------
# linstor node interface create alpha 100G_nic 192.168.43.221
# linstor node interface create alpha 10G_nic 192.168.43.231
----------------------------

NICはIPアドレスのみのよって識別され、名前は任意でありLinuxによって使用されるインターフェイス名には関連しません。NICはストレージプールに割り当てられますので、リソースがそのストレージプールに作成されるときは常にDRBDトラフィックはそのNICを介して行われます。

----------------------------
# linstor storage-pool set-property alpha pool_hdd PrefNic 10G_nic
# linstor storage-pool set-property alpha pool_ssd PrefNic 100G_nic
----------------------------

FIXME describe how to route the controller +<->+ client communication
through a specific `netif`.

[[s-linstor-encrypted-volumes]]
=== 暗号化ボリューム
LINSTORはDRBDボリュームの暗号化を透過的に扱うことができます。dm-cryptがストレージデバイスから提供されるストレージを暗号化するのに使われます。

暗号化の基本的な手順は以下になります。

1. コントローラでユーザセキュリティを無効にする（これは認証が実装されたあとに廃止になる予定です）
2. マスターパスフレーズを作成する
3. `--encrypt` オプションでボリューム定義を作成する
4. コントローラが再起動した後はマスターパスフレーズを再入力する

[[s-disable_user_security]]
==== ユーザセキュリティを無効にする
Linstorコントローラのユーザセキュリティを無効にする操作は、一度行えばその後はこれが継続します。手順は以下のとおりです。

1. `systemctl stop linstor-controller` でLinstorコントローラを止める
2. `/usr/share/linstor-server/bin/Controller -c /etc/linstor -d`
   でLinstorコントローラをデバッグモードで立ち上げる
3. デバックコンソールで `setSecLvl secLvl(NO_SECURITY)` を入力する
4. デバックシャットダウンコマンドの `shutdown` でlinstor-controllerを止める
5. `systemctl start linstor-controller` でコントローラを再び起動する


[[s-encrypt_commands]]
==== 暗号化のコマンド
以下にコマンドの詳細を示します。

LINSTORがボリュームを暗号化する前に、マスターパスフレーズを作ることが必要です。これには以下のlinstorコマンドを使用します。

----
# linstor encryption create-passphrase
----

`crypt-create-passphrase` はマスターパスフレーズを初期化するためにユーザの入力を待ちます。

マスターパスフレーズを変更したい場合は以下のコマンドで行います。

----
# linstor encryption modify-passphrase
----

ボリュームの暗号化を指定するには、ボリューム定義を作成するときに `--encrypt` フラグを追加します。例えば以下のように指定します。

----
# linstor volume-definition create crypt_rsc 1G --encrypt
----

マスターパスフェーズを入力する（コントローラを再起動した後）には以下を使用します。

----
# linstor encryption enter-passphrase
----

NOTE: linstor-controllerが再起動したときは、コントローラにマスターパスフェーズを常に入力する必要があります。そうしないとLINSTORは暗号化されたボリュームをオープンしたり作成したりできません。

[[s-linstor-snapshots]]
=== スナップショットの管理
スナップショットはthin LVMとZFSストレージプールでサポートされています。

[[s-creating_a_snapshot-linstor]]
==== スナップショットの作成
リソース定義 'resource1' がすでにどこかのノードにあると仮定すると、スナップショットは以下のコマンドで作成できます。

----------------------------
# linstor snapshot create resource1 snap1
----------------------------

これはリソースが存在するすべてのノードでスナップショットを作成します。LINSTORはリソースが使用中でも一貫性のあるスナップショットが取れることを保証します。

[[s-restoring_a_snapshot-linstor]]
==== スナップショットの復元
以下の手順では新しいリソースにスナップショットを復元します。オリジナルのリソースがそれが取られたノードからすでに削除されていても復元可能です。

最初にスナップショットに一致するボリュームをもつリソースを定義します。

----------------------------
# linstor resource-definition create resource2
# linstor snapshot volume-definition restore --from-resource resource1 --from-snapshot snap1 --to-resource resource2
----------------------------

この時点で必要に応じて追加の設定を適用します。それで準備ができたら、スナップショットを使ってリソースを作成します。

----------------------------
# linstor snapshot resource restore --from-resource resource1 --from-snapshot snap1 --to-resource resource2
----------------------------

これにより、スナップショットが存在するすべてのノードに新しいリソースが作られます。リソースを作るノードも明示的に指定できます。詳細はヘルプ
(`linstor snapshot resource restore -h`) を参照ください。

[[s-removing_a_snapshot-linstor]]
==== スナップショットの削除
スナップショットの削除は以下のコマンドで行います。

----------------------------
# linstor snapshot delete resource1 snap1
----------------------------

[[s-linstor-status]]
=== クラスタの状態をチェック
LINSTORにはクラスタの状態をチェックするいろいろなコマンドがあります。これらには 'list'
サブコマンドを使用し、フィルターしたりソートしたりするいろいろなオプションを提供します。'--groupby'
オプションは出力のグルーピングとソートに使います。

----------------------------
# linstor node list
# linstor storage-pool list --groupby Size
----------------------------

[[s-linstor-setupopts]]
=== リソースのオプション設定

DRBDのオプションはLINSTORコマンドで設定します。LINSTORによって管理されていない
`/etc/drbd.d/global_common.conf`
のような構成ファイルは無視されます。以下のコマンドで使用法と有効なオプションが表示されます。

----------------------------
# linstor controller drbd-options -h
# linstor resource-definition drbd-options -h
# linstor volume-definition drbd-options -h
# linstor resource drbd-peer-options -h
----------------------------

例えばリソース名 `backups` のDRBDプロトコルを設定するには以下のようにします。

----------------------------
# linstor resource-definition drbd-options --protocol C backups
----------------------------

[[s-linstor-proxy]]
=== LINSTORによるDRBD Proxy

LINSTORを使用して、遠隔地へのレプリケーション用にDRBD Proxyを構成できます。 DRBDプロキシを使用するには
<<s-using-drbd-proxy>> に説明されている通り、別途インストールとライセンスが必要になります。

LINSTORは、DRBD Proxyが接続するノード上で実行されることを期待しています。別のノードのDRBD
Proxy経由の接続は、今のところサポートしていません。

ここでクラスタが、ローカルネットワーク内のノード 'alpha' と 'bravo' とリモートサイトの 'charlie'
で構成され、各ノードに配備されるリソースは `backups` と仮定すると、DRBD Proxyを使用した 'charlie'
への接続を有効にするには以下のようにします。

----------------------------
# linstor drbd-proxy enable alpha charlie backups
# linstor drbd-proxy enable bravo charlie backups
----------------------------

DRBD Proxyのオプションは、次のコマンドで設定できます。

----------------------------
# linstor drbd-proxy options backups --memlimit 100000000
# linstor drbd-proxy compression zlib backups --level 9
----------------------------

LINSTORは遠隔地へのレプリケーション用にDRBD構成を自動的には最適化しないので、プロトコルなどのいくつかの構成オプションを設定することをお勧めします。

----------------------------
# linstor resource-connection drbd-options alpha charlie backups --protocol A
# linstor resource-connection drbd-options bravo charlie backups --protocol A
----------------------------

設定を最適化するには、LINBITにお問い合わせください。

[[s-linstor-rebalance]]
=== LINSTORでデータ再調整
FIXME

[[s-linstor-external-database]]
=== 外部データベース

LINSTORはPostgresqlやMariaDBのような外部データベースとともに動作させることもできます。外部データベースを動作させるには、いくつかの追加構成が必要になります。

1. 使用するデータベースのJDBCデータベースドライバをダウンロードし、LINSTORライブラリディレクトリにインストールします。
2. 使用するデータベースに合わせて、`/etc/linstor/database.cfg` ファイルを更新します。

[[s-postgresql]]
==== Postgresql

Postgresql JDBCドライバは以下からダウンロードできます。

https://jdbc.postgresql.org/download.html

そして、 `/usr/share/linstor-server/lib/` にコピーします

Postgresqlのサンプル `database.cfg` は以下のようになります。

------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
  <comment>LinStor MariaDB configuration</comment>
  <entry key="user">linstor</entry>
  <entry key="password">linstor</entry>
  <entry key="connection-url">jdbc:postgresql://localhost/linstor</entry>
</properties>
------------------------------------------------------

[[s-mariadb_mysql]]
==== MariaDB/Mysql

MariaDB JDBCドライバは以下からダウンロードできます。

https://downloads.mariadb.org/connector-java/

そして、 `/usr/share/linstor-server/lib/` にコピーします

MariaDBのサンプル `database.cfg` は以下のようになります。

------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
  <comment>LinStor MariaDB configuration</comment>
  <entry key="user">linstor</entry>
  <entry key="password">linstor</entry>
  <entry key="connection-url">jdbc:mariadb://localhost/LINSTOR?createDatabaseIfNotExist=true</entry>
</properties>
------------------------------------------------------

NOTE: LINSTORの schema/database は `LINSTOR` として作成されます。よって、mariadbの接続が `LINSTOR`
schema を参照していることを確認してください。

[[s-linstor-getting-help]]
=== ヘルプの利用
WRITE MAN PAGE

コマンドラインで利用可能なコマンドを確認するには `linstor` とタイプします。

サブコマンドのさらなる情報は次の２つの方法で確認できます。

----------------------------
# linstor node list -h
# linstor help node list
----------------------------

LINSTORがインタラクティブモード(`linstor interactive`)で動作しているときには 'help'
サブコマンドはとても役にたちます。

LINSTORで役に立つ機能の１つに豊富なタブ補完機能があります。これはLINSTORが認識する基本的なすべてのオブジェクト（例えばノード名、IPアドレス、リソース名など）を完成させるために使用できます。以下の例では、いくつかの可能な補完とその結果を示します。

----------------------------
# linstor node create alpha 1<tab> # ホスト名が解決できるとIPアドレスを補完します
# linstor resource create b<tab> c<tab> # linstorは backups, charlieリソースを補完します
----------------------------

タブ補完機能が動作しない場合は以下のファイルをソースしてください。

----------------------------
# source /etc/bash_completion.d/linstor # または
# source /usr/share/bash_completion/completions/linstor
----------------------------

zsh ユーザのためにlinstor-clientはzshタブ補完機能用のファイルを生成できます。これはコマンドと引数の基本的なサポート機能です。

----------------------------
# linstor gen-zsh-completer > /usr/share/zsh/functions/Completion/Linux/_linstor
----------------------------
