[[ch-install-packages]]
== コンパイル済みDRBDバイナリパッケージのインストール


[[s-linbit-packages]]
=== LINBIT社が提供するパッケージ

DRBDプロジェクトのスポンサー企業であるLINBIT社は、商用サポート対象のお客様向けにDRBDバイナリパッケージを提供しています。これらパッケージはリポジトリ
(`apt`, `yum`,その他用)から利用でき、「公式」DRBDビルドです。

これらのビルドは次のディストリビューションで入手できます。

* Red Hat Enterprise Linux (RHEL)バージョン6 、7

* SUSE Linux Enterprise Server (SLES)バージョン11SP4、12

* Debian GNU/Linux 8 (jessie)、9 (stretch)

* Ubuntu Server Edition LTS 14.04 (Trusty Tahr)、LTS 16.04 (Xenil Xerus)、LTS
  18.04 (Bionic Beaver)

他のディストリビューションのビルドも用意していますが、十分なテストは経ていません。

LINBIT社では、新規のDRBDソースのリリースと並行してバイナリビルドをリリースしています。

RPMベースのシステム(SLES、RHEL)へのパッケージのインストールは`yum install`(新規インストールの場合)または`yum
update`(アップグレードの場合)コマンドを呼び出すことで簡単に行えます。

Debianベースのシステム(Debian GNU/Linux、Ubuntu)では、 `drbd-utils` と `drbd-dkms` パッケージを
`apt` または、 `aptitude` や `synaptic` 等のツールを利用してインストールしてください。

[[s-docker-registry]]
=== LINBIT社が提供する Docker イメージ
LINBITは商用サポートカスタマー向けにDockerレポジトリを提供します。レポジトリはホスト名 'drbd.io'
経由でアクセスします。イメージを取得する前にレポジトリにログインする必要があります。

---------------------------------------
# docker login drbd.io
---------------------------------------

ログインに成功するとイメージを取得できます。ログインしてテストするには以下のコマンド実行してください。

---------------------------------------
# docker pull drbd.io/alpine
# docker run -it --rm drbd.io/alpine # press CTRL-D to exit
---------------------------------------

[[s-distro-packages]]
=== ディストリビューションベンダが提供するパッケージ

コンパイル済みバイナリパッケージを含め、いくつかのディストリビューションでDRBDが配布されています。これらのパッケージに対するサポートは、それぞれのディストリビュータが提供します。リリースサイクルは、DRBDソースのリリースより遅れる場合があります。

[[s-suse_linux_enterprise_server]]
==== SUSE Linux Enterprise Server

SLES High Availability Extension (HAE) includes DRBD.


SLESの場合、DRBDは通常はYaST2のソフトウェアインストールコンポーネントによりインストールされます。これは High
Availabilityパッケージセレクションに同梱されています。

コマンドラインを使用してインストールする場合は、次のコマンドを実行します。

---------------------------------------
# yast -i drbd
---------------------------------------

または

---------------------------------------
# zypper install drbd
---------------------------------------


[[s-centos]]
==== CentOS

CentOSのリリース5からDRBD 8が含まれています。DRBD 9はEPEL等から探してください。

DRBDは `yum` でインストールします。この際には、正しいリポジトリが有効である必要があります。

---------------------------------------
# yum install drbd kmod-drbd
---------------------------------------


[[s-ubuntu_linux]]
==== Ubuntu Linux

LINBITはUbuntu LTS用にPPAリポジトリを提供しています。
https://launchpad.net/~linbit/`archive/ubuntu/linbit-drbd9-stack.
詳細は以下をご確認ください。
https://help.ubuntu.com/community/Repositories/CommandLine#Adding_Launchpad_PPA_Repositories[Adding
Launchpad PPA Repositories]

---------------------------------------
# apt install drbd-utils python-drbdmanage drbd-dkms
---------------------------------------

[[s-from-source]]
=== ソースからパッケージをコンパイルする

https://github.com/LINBIT[github] で git tags によって生成されたリリースはある時点での git
レポジトリのスナップショットです。これらはマニュアルページや configure
スクリプト、あるいはその他の生成されるファイルが不足しているかもしれません。tarball からビルドするなら、
https://www.linbit.com/en/drbd-community/drbd-download/[DRBD Community
Download] を使用してください。

すべてのプロジェクトは標準のビルドスクリプト (eg, `Makefile`, `configure`)
を含みます。ディストリビューション毎に固有の情報をメンテナンスすることは手間がかかり、また歴史的にすぐに最新でなくなってしまいました。標準的な方法でソフトウェアをビルドする方法を知らない場合は、LINBITによって供給されるパッケージを使ってください。

