[[ch-kubernetes]]
== Kubernetes で LINSTOR ボリューム

indexterm:[Kubernetes]この章では
https://github.com/LINBIT/linstor-external-provisioner[Linstor External
Provisioner] と https://github.com/LINBIT/linstor-flexvolume[Linstor
FlexVolume Provisioner] の両方を使ってKubernetesでのDRBD使用方法を説明します。

External Provisionerはボリュームの作成と削除を行い、一方、FlexVolume
Provisionerはボリュームの接続、切り離し、マウント、アンマウント、ファイルシステムの作成を行います。

[[s-kubernetes-overview]]
=== Kubernetesの概要

KubernetesはGoogleによって作成されたコンテナのオーケストレータです。Kubernetesは宣言された仕様に基づいてコンテナと関連サービスを動作を定義します。

[[s-kubernetes-linstor-external-provisioner-installation]]
=== Linstor External Provisioner のインストール

External Provisionerのビルド方法は
https://github.com/LINBIT/linstor-external-provisioner[プロジェクトの github]
を参照ください。外部依存性をもたないネイティブバイナリが作成されます。

Linstor External
ProvisionerはLinstorクライアントがあるどのマシンでも実行できます。そしてLinstorコントローラとKubernetes
APIサーバ両方と通信します。

linstor-external-provisionerは `provisioner` オプションで名前を、 `kubeconfig`
オプションでKubernetes configの場所を指定して起動します。

----
# ./linstor-external-provisioner -provisioner=external/linstor -kubeconfig=$HOME/.kube/config
----

あるいははKubernetes masterのアドレスを指定して起動します。

----
# ./linstor-external-provisioner -provisioner=external/linstor -master=http://0.0.0.0:8080
----

一度スタートすると、Provisionerは `stdout` と `stderr`
を出力しますので、他の場所にリダイレクトして使用するのもよいかもしれません。

[[s-kubernetes-linstor-flexvolume-provisioner-installation]]
=== Linstor FlexVolume Provisioner のインストール

FlexVolume Provisionerのビルド方法は、
https://github.com/LINBIT/linstor-flexvolume[プロジェクトの github]
を参照ください。外部依存性をもたないネイティブバイナリが作成されます。

作成されたバイナリはすべてのkubeletノードの以下の場所にインストールする必要があります。

----
/usr/libexec/kubernetes/kubelet-plugins/volume/exec/linbit~linstor-flexvolume/
----

Kubernetesのバージョン1.8より前の場合は、インストール後、それぞれのノードで、kubeletプロセスを再起動する必要があります。

すべてのkubeletsノードで `--enable-controller-attach-detach=false`
オプションも設定し、プロセスを再起動する必要があります。systemdで管理されたkubeletsの場合は
`/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` に設定します。

さらにすべてのkubeletsノードは `linstor`
コマンドがPATHになければならず、LinstorクライアントはボリュームのStorageClassで定義されたコントローラと通信できなければなりません。

[[s-kubernetes-basic-configuration-and-deployment]]
=== 基本的な構成と配備

Linstorクライアントと動作するために、External Provisionerを実行し、すべてのkubeletsノードにFlexVolume
Provisionerをインストールすることで、Kubernetesワークフローを使用してボリュームを用意できます。

定義され配備されるLinstorボリュームの挙動とプロパティの構成はKubernetes
StorageClassesを使って設定されます。以下はボリュームを配備するのに使う簡単なStorageClassの例です。

----
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  # The name used to identify this StorageClass.
  name: two-replica
  # The name used to match this StorageClass with a provisioner.
  # This corresponds to the provisioner flag passed to the external provisioner.
provisioner: external/linstor
parameters:
  # Create volumes replicated across two nodes, and place them automatically.
  autoPlace: "2"
  # Volumes will be formatted with an xfs filesystem at mount time, if not already present.
  filesystem: "xfs"
  # Linstor will provision volumes from the drbdpool storage pool.
  storagePool: "drbdpool"
  # Comma-separated list of Linstor Controller processes that will provision volumes.
  controllers: "192.168.10.10:8080,172.0.0.1:3366"
----

ファイル名は `two-replica-sc.yaml` であると仮定し、以下のコマンドでStorageClassを作成できます。

----
kubectl create -f two-replica-sc.yaml
----

StorageClassが作成されましたので、次はKubernetesとLinstor両方で使われるボリュームを作成するPersistentVolumeClaimsを使います。

----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-first-volume
  annotations:
    # This line matches the PersistentVolumeClaim with our StorageClass
    # and therefore our provisioner.
    volume.beta.kubernetes.io/storage-class: two-replica
  spec:
    accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
----

ファイル名は `my-first-volume-pvc.yaml`
であると仮定し、以下のコマンドでPersistentVolumeClaimを作成できます。

----
kubectl create -f my-first-volume-pvc.yaml
----

これによりKubernetesに認識されてPersistentVolumeがバインドされ、PersistentVolumeClaimが作成されます。さらにLinstorがtwo-replica
StorageClassで定義さらた構成にしたがってボリュームを作成します。Linstorのボリューム名とPersistentVolumenの名前はPVC's
Kubernetesの名前空間によって付加されたPersistentVolumeClaim名になります。例えばKubernetes今作成したLinstorボリュームがdefault名前空間だった場合は
`default-my-first-volume` と名付けられます。これは `linstor resource list`
で確認できます。一度ボリュームが作成されると同じ方法でそれをpodに割れ当てられます。以下のpod仕様はFedoraコンテナを作成し、ビジーウェイトにするので、アンスケジュールされません。

----
apiVersion: v1
kind: Pod
metadata:
  name: fedora
  namespace: default
spec:
  containers:
  - name: fedora
    image: fedora
    command: [/bin/bash]
    args: ["-c", "while true; do sleep 10; done"]
    volumeMounts:
    - name: default-my-firt-volume
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: default-my-first-volume
    persistentVolumeClaim:
      claimName: "my-first-volume"
----

`kubectl describe pod fedora` を実行することでpodがスケジュールされ、ボリュームが正しく割り当てられたのを確認できます。

ボリュームを削除するにはpodでもう使われていないことを確認してから、`kubectl`
を使ってPersistentVolumeClaimを削除します。例えば、先ほど作成したボリュームを削除するには、以下のコマンドを実行します。ボリュームが削除される前にpodがアンスケジュールされていなければならないことに注意してください。

----
kubectl delete pod fedora # podをアンスケジュール。

kubectl get pod -w # podがアンスケジュールされるまで待つ

kubectl delete pvc my-first-volume # PersistentVolumeClaim、PersistentVolume、Linstorボリュームを削除する。
----


[[s-kubernetes-advanced-configuration]]
=== 高度な設定

KubernetesのLinstorボリュームのすべての構成は、上で使用したサンプルのようにstorageクラスのパラメータ経由で設定されます。以下にすべての利用なオプションの詳細を示します。

[[s-autoplace]]
==== autoPlace

`autoPlace` このStorageClassが持つボリュームの複製数を指定します。例えば、 `autoPlace: 3`
は３つの複製をもつボリュームを生成します。`autoPlace` または `nodeList`
が指定されていない場合は、１つのノード上にボリュームが生成されます。

例: `autoPlace: 2`

[[s-blocksize]]
==== blockSize

`blockSize` はオプションでxfsまたはext4でファイルシステム作成時のブロックサイズを指定します。

例: `blockSize: 2048`

[[s-controllers]]
==== controllers

`controllers`
はカンマで区切られたLinstorコントローラのリストで通常は必須パラメータです。ただし、コントローラがkubeletノードと同じノードで動作しているような、１ノードのテストクラスターのような環境では必須ではありません。

例: `controllers: "192.168.10.10:8080,172.0.0.1:3366"`

[[s-disklessstoragepool]]
==== disklessStoragePool

`disklessStoragePool`
はオプションでノードがkubeletsにディスクレス、すなわちクライアントとして割り当てられるようにするときに使用します。Linstor
でカスタムディスクレスストレージプールが定義されている場合は、ここで指定します。

例: `disklessStoragePool: my-custom-diskless-pool`

[[s-donotplacewithregex]]
==== doNotPlaceWithRegex

`doNotPlaceWithRegex`
はオプションで、Linstorが正規表現とマッチするリソースを他のリソースと一緒に置かないようにします。例えばPersistentVolumeClaimとして
`cats` があり、PersistentVolumeClaims `dogs` と `doughnuts`
と同じノードに置きたくない場合は、名前空間の接頭辞も考慮して次のように指定します。

例: `^default-do.*`

[[s-encryption]]
==== encryption

`encryption`
はオプションで、ボリュームを暗号化するかどうかを指定します。Linstorはこれが正しく動作するように適切に設定されている必要があります。

Example: `encryption: "yes"`

[[s-force]]
==== force

`force` はオプションで、マウント時にファイルシステムの作成を強制的に行います。

例: `force: "true"`

[[s-nodelist]]
==== nodeList

`nodeList` ボリュームが割り当てられるノードのリストです。ボリュームがそれぞれのノードに割り当てられそれらの間で複製が行われます。

例: `nodeList: "node-a node-b node-c"`

[[s-storagepool]]
==== storagePool

`storagePool` はLinstorのストレージプールの名前で、新規に作成されたボリュームにストレージを供給するときに使用されます。

例: `storagePool: my-storage-pool`

`mountOpts` はオプションで、マウント時にボリュームのファイルシステムに渡すオプションを指定します。

例: `mountOpts: "sync,noatime"`

[[s-xfs_specific_parameters]]
==== xfs固有のパラメータ

以下はオプションで、ファイルシステム作成時に影響を与えるxfsのチューニングパラメータです。

`xfsDataSU` はmkfs.xfsの `-d su` に対応します。

例: `xfsDataSU: "64k"`

`xfsDataSW` はmkfs.xfsの `-d sw` に対応します。

例: `xfsDataSW: "4"`

`xfsLogDev` はmkfs.xfsの `-l logdev` に対応します。

例: `xfsLogDev: "/dev/example"`

`xfsdiscardblocks` はmkfs.xfsの `-K`
オプションに対応します。デフォルトはブロックを破棄しません。xfsのデフォルトの動作はブロックを破棄します。

例: `xfsdiscardblocks: "true"`
