[[ch-more-info]]
== 詳細情報の入手

[[s-commercial-support]]
=== 商用DRBDのサポート

DRBDの商用サポート、コンサルティング、トレーニングサービスは、プロジェクトのスポンサ企業LINBIT社が提供しています。日本ではhttp://www.linbit.com/[LINBIT]社との提携にもとづいて株式会社サードウェアが各種サポートを提供しています。

[[s-mailing-list]]
=== 公開メーリングリスト

DRBDの一般的な使用法について質問がある場合は、公開メーリングリスト drbd-user@lists.linbit.com
にお問い合わせください。このメーリングリストは登録が必要です。 http://lists.linbit.com/drbd-user/
で登録してください。リスト全体のアーカイブは http://lists.linbit.com/pipermail/drbd-user/ にあります。

[[s-irc-channels]]
=== 公開IRCチャンネル

公開IRCサーバ `irc.freenode.net` の次のチャンネルに、DRBDの開発者も参加しています。

* `#drbd`, and
* `#clusterlabs`.

IRCを使って、DRBDの改善を提案したり、開発者レベルの議論をすることもあります。

問題について質問する際にはDRBDの設定、ログファイル、 `drbdsetup status --verbose --statistics` の結果、
`/proc/drbd` の内容を提供してください。これらの情報がない場合には回答は困難です。


[[s-twitter-account]]
=== 公式twitterアカウント

http://www.linbit.com/[LINBIT]はツイッターをやっています。こちらです:http://twitter.com/linbit[`linbit`]

DRBDについてツイートする時には、どうぞ `#drbd` のハッシュタグをお使いください。

[[s-publications]]
=== 資料

DRBDの開発者により作成されたDRBD一般やDRBDの特定の機能についての文書が公開されています。その一部を次に示します。

[bibliography]
- Philipp Reisner. 'DRBD 9 - What's New'. 2012. Available at
  http://www.drbd.org/fileadmin/drbd/publications/whats-new-drbd-9.pdf
	// FIXME only bad version at
	https://www.netways.de/fileadmin/images/Events_Trainings/Events/OSDC/2013/Slides_2013/Philipp_Reisner_Neues_in_DRBD9.pdf
	// FIXME - put fixed version there
- Lars Ellenberg. 'DRBD v8.0.x and beyond'. 2007. Available at
  http://drbd.linbit.com/fileadmin/drbd/publications/drbd8.linux-conf.eu.2007.pdf
- Philipp Reisner. 'DRBD v8 - Replicated Storage with Shared Disk
  Semantics'. 2007. Available at
  http://drbd.linbit.com/fileadmin/drbd/publications/drbd8_orig.pdf FIXME sagt
  2005?
- Philipp Reisner. 'Rapid resynchronization for replicated
  storage'. 2006. Available at
  http://drbd.linbit.com/fileadmin/drbd/publications/drbd-activity-logging_v6.pdf.

You can find many more on http://drbd.linbit.com/home/publications/.

[[s-useful-resources]]
=== その他の資料

* Wikipediaにはhttp://en.wikipedia.org/wiki/DRBD[DRBDの記事]があります。
* http://wiki.linux-ha.org/[Linux-HA wiki]と
* http://www.clusterlabs.org[ClusterLabs
  website]に、高可用性クラスタでDRBDを活用するための有益な情報があります 。
