[[ch-throughput]]
== DRBDのスループット最適化

この章では、DRBDのスループットの最適化について説明します。スループットを最適化するためのハードウェアに関する検討事項と、チューニングを行う際の詳細な推奨事項について取り上げます。

[[s-throughput-hardware]]
=== ハードウェアの検討事項

DRBDのスループットは、配下のI/Oサブシステム(ディスク、コントローラおよび対応するキャッシュ)の帯域幅とレプリケーションネットワークの帯域幅の両方の影響を受けます。

.I/Oサブシステムのスループット
indexterm:[throughput]
I/Oサブシステムのスループットは主に並行して書き込み可能なストレージユニットの数と種類(ハードディスク、SSD、その他のフラッシュストレージ{FusionIOなど}...)によって決まります。比較的新しいSCSIまたはSASディスクの場合、一般に1つのディスクに約40MB/sでストリーミング書き込みを行うことができます。SSDなら300MiB/s、最新のフラッシュストレージ(NVMe)なら1GiB/sほどになります。ストライピング構成で配備する場合は、I/Oサブシステムにより書き込みがディスク間に並列化されます。
この場合、スループットは、1つのディスクのスループットに構成内に存在するストライプの数を掛けたものになります。RAID-0またはRAID-1`0構成で、
3つのストライプがある場合は同じ40MB/sのディスクのスループットが120MB/sになり、5つのストライプがある場合は200MB/sになります。SSDとNVMeまたはNVMeのみで構成すれば容易に1GiB/s超になるでしょう。

バッテリーバックアップされたバッファメモリを持つRAIDコントローラでは少量の書き込みの速度は、それらがバッファリングされることによって大幅に加速されます。非常に短い測定テストでは1GiBを示すかもしれません。持続的な書き込みではバッファがフルになるので速度は低下します。


NOTE: ハードウェアのディスク_ミラーリング_(RAID-1)は、一般にスループットにはほとんど影響ありません。ディスクの_パリティ付きストライピング_(RAID-5)はスループットに影響し、通常はストライピングに比べてスループットが低下します。ソフトウェアRAIDのRAID-5やRAID-6であればさらに低下します。

.ネットワークのスループット
indexterm:[throughput]ネットワークスループットは一般にネットワーク上に存在するトラフィック量と経路上にあるルータやスイッチなどのスループットによって決定されます。ただし、DRBDのレプリケーションリンクは通常は専用の背面間ネットワーク接続であるため、これらはあまり関係がありません。したがって、ネットワークのスループットを向上させるには、高スループットのプロトコル(10ギガビットイーサネットや56GiBインフィニバンド)に切り換えるか、複数のネットワークリンクからなるリンクアグリゲーションを使用します。後者はLinux
indexterm:[bonding driver]`bonding` ネットワークドライバを使用して実現できます。

[[s-throughput-overhead-expectations]]
=== スループットオーバヘッドの予測

DRBDに関連するスループットオーバヘッドを見積もる際には、 必ず次の制限を考慮してください。

* DRBDのスループットは下位I/Oサブシステムのスループットにより制限される。
* DRBDのスループットは使用可能なネットワーク帯域幅により制限される。

DRBDが使用できる理論上の _最大_ スループットは上記の _小さい方_
によって決まります。この最大スループットはDRBD自体のスループットオーバヘッドが加わることにより低下しますが、 これは3%未満だと考えられます。

* たとえば、600MB/sのスループットが可能なI/Oサブシステムを持つ2つのクラスタノードが、 ギガビットイーサネットリンクで接続されているとします
  。ギガビットイーサネットのスループットは 110MB/s程度だと考えられるため、 この構成ではネットワーク接続がボトルネックになります。
  DRBDの最大スループットは110MB/s程度でしょう。

* 一方、I/Oサブシステムの持続した書き込みスループットが80MB/s程度の場合は、これがボトルネックとなり、DRDBの最大スループットはわずか77MB/sになります。


[[s-throughput-tuning]]
=== チューニングの推奨事項

DRBDには、システムのスループットに影響する可能性があるいくつかの構成オプションがあります。ここでは、スループットを向上させるための調整について、いくつかの推奨事項を取り上げます。ただし、スループットは主としてハードウェアに依存するため、ここで取り上げるオプションを調整しても、効果はシステムによって大きく異なります。パフォーマンスチューニングについて、必ず効く「特効薬」は存在しません。

[[s-tune-max-buffer-max-epoch-size]]
==== `max-buffers` と `max-epoch-size` の設定

これらのオプションはセカンダリノードの書き込みパフォーマンスに影響します。`max-buffers`
はディスクにデータを書き込むためにDRBDが割り当てるバッファの最大数で、 `max-epoch-size`
は、2つの書き込みバリア間で許容される書き込み要求の最大数です。パフォーマンスを上げるためには `max-buffers` は
`max-epoch-size` 以上でなければなりません。
デフォルト値は両方とも2048です。比較的高パフォーマンスのハードウェアRAIDコントローラの場合、この値を8000程度に設定すれば十分です。

[source, drbd]
----------------------------
resource <resource> {
  net {
    max-buffers    8000;
    max-epoch-size 8000;
    ...
  }
  ...
}
----------------------------

[[s-tune-sndbuf-size]]
==== TCP送信バッファサイズの調整

TCP送信バッファは送信TCPトラフィックのメモリバッファです。デフォルトサイズは128KiBです。高スループットネットワーク
(専用ギガビットイーサネット、負荷分散ボンディング接続など)で使用する場合は、このサイズを2MiBかそれ以上に設定すると効果があるでしょう。送信バッファサイズを16MiB以上にすることは一般にはお勧めできません。
また、スループットが向上する可能性もありません。

[source, drbd]
----------------------------
resource <resource> {
  net {
    sndbuf-size 2M;
    ...
  }
  ...
}
----------------------------

TCP送信バッファの自動調整もサポートされます。この機能を有効にすると、DRBDが適切なTCP送信バッファサイズを動的に選択します。TCP送信バッファの自動調整を有効にするには、次のようにバッファサイズをゼロに設定します。

[source, drbd]
----------------------------
resource <resource> {
  net {
    sndbuf-size 0;
    ...
  }
  ...
}
----------------------------

`sysctl` 設定の `net.ipv4.tcp_rmen` と `net.ipv4.tcp_wmem`
は挙動に影響します。これらの設定を確認してください。またこれらを `131072 1048576 16777216`
(最小128kiB、デフォルト1MiB、最大16MiB)にするとよいかもしれません。

WARNING: `net.ipv4.tcp_mem`
はまったく異なるものですので、変更しないでください。間違った値を指定すると、容易にマシンがout-of-memoryになってしまいます。

[[s-tune-al-extents]]
==== アクティビティログサイズの調整

DRBDを使用するアプリケーションが、デバイス全体に分散した小さな書き込みを頻繁に発行する、書き込み集約型の場合は、十分に大きなアクティビティログを使用することをお勧めします。そうでない場合、頻繁なメタデータ更新により書き込みパフォーマンスが低下する可能性があります。

[source, drbd]
----------------------------
resource <resource> {
  disk {
    al-extents 6007;
    ...
  }
  ...
}
----------------------------


[[s-tune-disable-barriers]]
==== バリアとディスクフラッシュを無効にする

WARNING: 次に取り上げる推奨事項は、不揮発性(バッテリでバックアップされた)のコントローラキャッシュのあるシステム _のみ_ に適用されます。

バッテリでバックアップされた書き込みキャッシュを持つシステムには、停電時にデータを保護する機能が組み込まれています。その場合は、同じ目的を持つDRBD自体の保護機能の一部を無効にすることもできます。これはスループットの面で有効な場合があります。

[source, drbd]
----------------------------
resource <resource> {
  disk {
    disk-barrier no;
    disk-flushes no;
    ...
  }
  ...
}
----------------------------


[[s-tune-read-balancing]]
=== 冗長性を高め読み込み性能を向上させる

`drbd.conf` マニュアルページの `read-balancing`
で説明の通り、データのコピーを追加することで読み込み性能を上げることができます。

概算: FusionIO カード利用の１ノードでの読み込み要求が `fio` では100kIOPsでしたが、 `read-balancing`
を利用したた場合にはパフォーマンスが180kIOPsとなり、80%の性能向上が見られました!

読み込みのワークロードが多い環境の場合(ランダムリードが多い巨大なデータベースなど)では、read-balancing
を有効にする意義があります。さらに読み込みIOスループットが欲しい場合にはコピーを増やすとよいでしょう。

