[[ch-install-packages]]
== Installing prebuilt DRBD binary packages

[[s-linbit-packages]]
=== LINBIT supplied packages

LINBIT, the DRBD project's sponsor company, provides binary packages to its commercial support customers.
These packages are available through repositories and package manager commands (for example, `apt`, `dnf`), and when reasonable through LINBIT's Docker
registry. Packages and images from these sources are considered "official" builds.

These builds are available for the following distributions:

* Red Hat Enterprise Linux (RHEL), versions 7, 8 and 9

* SUSE Linux Enterprise Server (SLES), versions 12 and 15

* Debian GNU/Linux, 9 (stretch), 10 (buster), and 11 (bullseye)

* Ubuntu Server Edition LTS 18.04 (Bionic Beaver), LTS 20.04 (Focal Fossa), and LTS 22.04 (Jammy Jellyfish)

* Oracle Linux (OL), versions 8 and 9

Refer to the <<s-ko-signing>> section for information about which specific DRBD kernel modules
have signed packages for which distributions.

Packages for some other distributions are built as well, but don't receive as much testing.

LINBIT releases binary builds in parallel with any new DRBD source
release.

Package installation on RPM-based systems (SLES, RHEL, AlmaLinux) is done by
simply using `dnf install` (for new installations) or `dnf update` (for
upgrades).

For DEB-based systems (Debian GNU/Linux, Ubuntu) systems,
`drbd-utils` and `drbd-module-`uname -r`` packages are installed by using `apt install`,

ifndef::de-brand[]
[[s-linbit-manage-node-script]]
==== Using a LINBIT helper script to register nodes and configure package repositories

If you are a LINBIT customer, you can install DRBD and dependencies that you may need from
LINBIT's customer repositories. To access those repositories you will need to have been set up
in LINBIT's system and have access to the link:https://my.linbit.com/[LINBIT Customer Portal].
If you have not been set up in LINBIT's system, or if you want an evaluation account, you can
contact a sales team member: sales@linbit.com.

[[s-linbit-manage-node-script-register-nodes]]
===== Using the LINBIT Customer Portal to register nodes

Once you have access to the LINBIT Customer Portal, you can register your cluster nodes and
configure repository access by using LINBIT's Python helper script. See the
https://my.linbit.com/#/reg_nodes[Register Nodes] section of the Customer Portal for details
about this script.

===== Downloading and running the LINBIT manage nodes helper script

To download and run the LINBIT helper script to register your nodes and configure LINBIT
repository access, enter the following commands on all nodes, one node at a time:

----
# curl -O https://my.linbit.com/linbit-manage-node.py
# chmod +x ./linbit-manage-node.py
# ./linbit-manage-node.py
----

IMPORTANT: The script must be run as superuser.

TIP: If the error message `no python interpreter found :-(` is displayed when running
`linbit-manage-node.py`, enter the command `dnf -y install python3` (RPM-based distributions) or
`apt -y install python3` (DEB-based distributions) to install Python 3.

The script will prompt you to enter your LINBIT Customer Portal username and password. After
validating your credentials, the script will list clusters and nodes (if you have any already
registered) that are associated with your account.

===== Joining nodes to a cluster

Select the cluster that you want to register the current node with. If you want the node to be
the first node in a new cluster, select the "new cluster" option.

===== Saving the registration and repository configurations to files

To save the registration information on your node, confirm the writing of registration data to a
JSON file, when the helper script prompts you to.

----
Writing registration data:
--> Write to file (/var/lib/drbd-support/registration.json)? [y/N]
----

To save the LINBIT repository configuration to a file on your node, confirm the writing of a
`linbit.repo` file, when the helper script prompts you to.

===== Enabling access to LINBIT repositories

After registering a node by using the LINBIT manage node helper script and joining the node to
a cluster, the script will show you a menu of LINBIT repositories.

To install DRBD, its dependencies, and related packages, enable the `drbd-9` repository.


NOTE: The `drbd-9` repository includes the latest DRBD 9 version. It also includes other LINBIT
software packages, including LINSTOR(R), DRBD Reactor, LINSTOR GUI, OCF resource agents, and
others.

===== Installing the LINBIT public key and verifying LINBIT repositories

After enabling LINBIT repositories and confirming your selection, be sure to respond *yes* to
the questions about installing LINBIT's public key to your keyring and writing the repository
configuration file.

Before it closes, the script will show a message that suggests different packages that you can
install for different use cases.

===== Verifying LINBIT repositories

After the LINBIT manage node helper script completes, you can verify that you enabled LINBIT
repositories by using the `dnf info` or `apt info` command, after updating your package
manager's package metadata.

On RPM-based systems, enter:

----
# dnf --refresh info drbd-utils
----

On DEB-based systems, enter:

----
# apt update && apt info drbd-utils
----

Output from the package manager `info` command should show that the package manager is pulling
package information from LINBIT repositories.

===== Excluding packages from Red Hat or AlmaLinux repositories

If you are using an RPM-based Linux distribution, before installing DRBD, be sure to only pull
DRBD and related packages from LINBIT repositories. To do this, you will need to exclude certain
packages from your RPM-based distribution's repositories that overlap with packages in the
LINBIT customer repositories.

The commands that follow insert an "exclude" line after the occurrence of every enabled
repository line in all files in the repositories configuration directory, except for LINBIT
repository files.

To exclude the relevant DRBD packages from enabled repositories on RPM-based distributions,
enter the commands:

----
# RPM_REPOS="`ls /etc/yum.repos.d/*.repo|grep -v linbit`"
# PKGS="drbd kmod-drbd"
# for file in $RPM_REPOS; do sed -i "/^enabled[ =]*1/a exclude=$PKGS" $file; done
----

===== Using the helper script's suggested package manager command to install DRBD

To install DRBD, you can use the package manager command that the LINBIT helper script showed
before the script completed. The relevant command was shown after this line:

----
If you don't intend to run an SDS satellite or controller, a useful set is:
[...]
----

[TIP]
====
If you need to refer to the helper script's suggested actions some time after the script
completes, you can run the script again using the `--hints` flag:

----
# ./linbit-manage-node.py --hints
----
====

IMPORTANT: On DEB based systems you can install a precompiled DRBD kernel module package,
`drbd-module-$(uname -r)`, or a source version of the kernel module, `drbd-dkms`. Install one
or the other package but not both.
endif::de-brand[]

[[s-ko-signing]]
==== LINBIT kernel module signing for secure boot
LINBIT signs most of its kernel module object files, the following table gives an overview when signing for distributions started:

[options="header"]
|===
| Distribution | Module signing since DRBD release
| RHEL7        | 8.4.12/9.0.25/9.1.0
| RHEL8        | 9.0.25/9.1.0
| RHEL9+       | all available
| SLES15       | 9.0.31/9.1.4
| Debian       | 9.0.30/9.1.3
| Ubuntu       | 9.0.30/9.1.3
| Oracle Linux | 9.1.17/9.2.6
|===

The public signing key is shipped in the RPM package and gets installed to
`/etc/pki/linbit/SECURE-BOOT-KEY-linbit.com.der`. It can be enrolled with the following command:

----
# mokutil --import /etc/pki/linbit/SECURE-BOOT-KEY-linbit.com.der
input password:
input password again:
----

A password can be chosen freely. It will be used when the key is actually enrolled to the MOK list after the
required reboot.

[[s-docker-registry]]
=== LINBIT supplied docker images
LINBIT provides a Docker registry for its commercial support customers. The registry is accessible through
the host name 'drbd.io'.

IMPORTANT: LINBIT's container image repository (http://drbd.io) is only available to LINBIT
customers or through LINBIT customer trial accounts.
link:https://linbit.com/contact-us/[Contact LINBIT for information on pricing or to begin a
trial]. Alternatively, you may use LINSTOR SDS' upstream project named
link:https://github.com/piraeusdatastore/piraeus-operator[Piraeus], without being a LINBIT
customer.

Before you can pull images, you have to log in to the registry:

----
# docker login drbd.io
----

After a successful login, you can pull images. To test your login and the registry, start by issuing the
following command:

----
# docker pull drbd.io/drbd-utils
# docker run -it --rm drbd.io/drbd-utils # press CTRL-D to exit
----

[[s-distro-packages]]
=== Distribution supplied packages

Several Linux distributions provide DRBD, including prebuilt binary
packages. Support for these builds, if any, is being provided by the
associated distribution vendor. Their release cycle may lag behind
DRBD source releases.

[[s-install-pkgs-suse_linux_enterprise_server]]
==== SUSE Linux Enterprise Server

SUSE Linux Enterprise Server (SLES) High Availability Extension (HAE) includes DRBD.

On SLES, DRBD is normally installed through the software installation
component of YaST2. It comes bundled with the High Availability
Extension package selection.

Users who prefer a command line install may simply issue:

----
# yast -i drbd
----

or

----
# zypper install drbd
----


[[s-install-pkgs-centos]]
==== CentOS

CentOS has had DRBD 8 since release 5; for DRBD 9 you will need examine EPEL
and similar sources.

DRBD can be installed using `yum` (note that you will need a
correct repository enabled for this to work):

----
# yum install drbd kmod-drbd
----


[[s-install-pkgs-ubuntu_linux]]
==== Ubuntu Linux

For Ubuntu LTS, LINBIT offers a PPA repository at
https://launchpad.net/~linbit/+archive/ubuntu/linbit-drbd9-stack.
See
https://help.ubuntu.com/community/Repositories/CommandLine#Adding_Launchpad_PPA_Repositories[Adding Launchpad PPA Repositories] for more information.

----
# apt install drbd-utils drbd-dkms
----

[[s-from-source]]
=== Compiling packages from source

Releases generated by Git tags on https://github.com/LINBIT[github] are snapshots of the Git repository at the
given time. You most likely do not want to use these. They might lack things such as generated man pages, the
`configure` script, and other generated files. If you want to build from a tar file, use the ones
https://linbit.com/linbit-software-download-page-for-linstor-and-drbd-linux-driver[provided by us].

All our projects contain standard build scripts (e.g., `Makefile`, `configure`). Maintaining specific
information per distribution (e.g., documenting broken build macros) is too cumbersome, and historically the
information provided in this section got outdated quickly. If you don't know how to build software the
standard way, please consider using packages provided by LINBIT.

///////

[[s-_debian_gnu_linux]]
====  Debian GNU/Linux

While PPAs are not directly supported in Debian, they basically work like any
other package repository. For `jessie` you should be able to just use
the `xenial` repository in your `sources.list`:

----
deb http://ppa.launchpad.net/linbit/linbit-drbd9-stack/ubuntu xenial main
----

Then use the same command to install the software:

----
# apt install drbd-utils drbd-dkms
----

///////
