[[ch-more-info]]
== Getting More Information

ifndef::de-brand[]
[[s-commercial-support]]
=== Commercial DRBD Support

Commercial DRBD support, consultation, and training services are
available from the project's sponsor company,
https://www.linbit.com/[LINBIT].
endif::de-brand[]

[[s-mailing-list]]
=== Public Mailing List

The public mailing list for general usage questions regarding DRBD is
drbd-user@lists.linbit.com. This is a subscribers-only mailing list,
you may subscribe at https://lists.linbit.com/listinfo/drbd-user/. A complete
list archive is available at
https://lists.linbit.com/pipermail/drbd-user/.

ifndef::de-brand[]
[[s-twitter-account]]
=== Official Twitter Account

https://www.linbit.com/[LINBIT] maintains an official https://twitter.com/linbit[Twitter account].

If you tweet about DRBD, please include the `#drbd` hashtag.
endif::de-brand[]

[[s-publications]]
=== Publications

DRBD's authors have written and published several papers on DRBD
in general, or a specific aspect of DRBD. Here is a short selection:

[bibliography]
- Philipp Reisner. https://web.archive.org/web/20180623151431/https://www.netways.de/fileadmin/images/Events_Trainings/Events/OSDC/2013/Slides_2013/Philipp_Reisner_Neues_in_DRBD9.pdf[DRBD 9 - What's New], 2012.

- Lars Ellenberg. https://web.archive.org/web/20190518224551/https://lap.snt.utwente.nl/dokuwiki/_media/projecten:storage:drbd8.linux-conf.eu.2007.pdf[DRBD v8.0.x and beyond], 2007.

- Philipp Reisner. https://web.archive.org/web/20150906225118/http://drbd.linbit.com/fileadmin/drbd/publications/drbd8_orig.pdf[DRBD v8 - Replicated Storage with Shared Disk
  Semantics], 2007.
- Philipp Reisner. https://web.archive.org/web/20150906225736/http://drbd.linbit.com/fileadmin/drbd/publications/drbd-activity-logging_v6.pdf[Rapid resynchronization for replicated
  storage], 2006.

// You can find many more on http://drbd.linbit.com/home/publications/.
// mat - link gets redirected to Software Downloads?
[[s-useful-resources]]
=== Other Useful Resources

* In addition to the user's guide you are reading now, LINBIT provides more documentation such
  as how-to guides, video tutorials, and explanatory blog posts that are available through the
  Documentation menu on its website, https://www.linbit.com.
* Wikipedia has https://en.wikipedia.org/wiki/DRBD[an entry on DRBD].
* Both the http://wiki.linux-ha.org[Linux-HA wiki] and https://www.clusterlabs.org[ClusterLabs website] have useful information
  about using DRBD in high-availability clusters.
