[[s-using-drbd-proxy]]
== Using DRBD Proxy

[[s-drbd-proxy-deployment-considerations]]
=== DRBD Proxy Deployment Considerations

The <<s-drbd-proxy,DRBD Proxy>> processes can either be located directly on the machines where
DRBD is set up, or they can be placed on distinct dedicated servers. A DRBD Proxy instance can
serve as a proxy for multiple DRBD devices distributed across multiple nodes.

DRBD Proxy is completely transparent to DRBD. Typically you will expect a high number of data
packets in flight, therefore the activity log should be reasonably large. Since this may cause
longer re-sync runs after the failure of a primary node, it is recommended to enable the DRBD
`csums-alg` setting.

For more information about the rationale for the DRBD Proxy, please see the feature explanation
<<s-drbd-proxy>>.

[[s-drbd-proxy-installation]]
=== Installing DRBD Proxy

DRBD Proxy is available to LINBIT customers with an appropriate contract.
If you want to try DRBD Proxy, link:https://linbit.com/contact-us/[contact the LINBIT team] to start
an evaluation.

DRBD Proxy can be installed from the LINBIT repositories.
For details of how to set up these repositories, see <<s-linbit-manage-node-script>>.
For DRBD Proxy version 4, enable the `drbd-proxy-4` repository.
For legacy DRBD Proxy version 3.2, enable the `drbd-proxy-3.2` repository.

Once the repository is set up, DRBD Proxy can be installed using your package manager.
For example:

----
# dnf install drbd-proxy
----

Or:

----
# apt install drbd-proxy
----

DRBD Proxy version 4 includes a systemd service.
It is not necessary to enable this service because the service is started by socket activation when
DRBD Proxy is configured using `drbdadm` or when `drbd-proxy-ctl` is used directly.

NOTE: DRBD Proxy version 3 includes an init script which usually goes into `/etc/init.d`. Always use
the init script to start or stop DRBD proxy since it also configures DRBD Proxy using the `drbdadm`
tool.

[[s-drbd-proxy-license]]
=== License File

When obtaining a license from LINBIT, you will be sent a DRBD Proxy license file which is
required to run DRBD Proxy. The file is called `drbd-proxy.license`, it must be copied into the
`/etc` directory of the target machines.

----
# cp drbd-proxy.license /etc/
----

NOTE: For DRBD Proxy version 3 the license file must be owned by the user and group `drbdpxy`.

[[s-drbd-proxy-configuration-linstor]]
=== Configuring DRBD Proxy Using LINSTOR

DRBD Proxy can be configured using LINSTOR as described in the
link:https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/[_LINSTOR User's Guide_].

[[s-drbd-proxy-configuration]]
=== Configuring DRBD Proxy Using Resource Files

DRBD Proxy can also be configured by editing resource files. It is configured by an additional
section called `proxy` and additional `proxy on` sections within the host sections.

Below is a DRBD configuration example for proxies running directly on the DRBD nodes:

[source,drbd]
----
resource r0 {
	protocol A;
	device     /dev/drbd15;
	disk       /dev/VG/r0;
	meta-disk  internal;

	proxy {
		memlimit 512M;
		plugin {
			zstd level 7;
		}
	}

	on alice {
		address 127.0.0.1:7915;
		proxy on alice {
			inside 127.0.0.1:7815;
			outside 192.168.23.1:7715;
		}
	}

	on bob {
		address 127.0.0.1:7915;
		proxy on bob {
			inside 127.0.0.1:7815;
			outside 192.168.23.2:7715;
		}
	}
}
----

The `inside` IP address is used for communication between DRBD and the DRBD Proxy, whereas the
`outside` IP address is used for communication between the proxies. The latter channel might
have to be allowed in your firewall setup.

[[s-drbd-proxy-controlling]]
=== Controlling DRBD Proxy

`drbdadm` offers the `proxy-up` and `proxy-down` subcommands to configure or delete the
connection to the local DRBD Proxy process of the named DRBD resource(s). When the `drbd-proxy`
service starts, it uses the `proxy-up` command to add the connections defined in the resource files.

The DRBD Proxy has a low level configuration tool, called `drbd-proxy-ctl`.

NOTE: With DRBD Proxy v3, commands are passed using the `-c` parameter.
For instance `drbd-proxy-ctl -c "show hconnections"`.

To display the available commands use:

----
# drbd-proxy-ctl --help
----

Here is a list of commands; while the first few ones are typically only used indirectly (via
`drbdadm proxy-up` resp. `drbdadm proxy-down`), the latter ones give various status information.

`add connection _<name>_ _lots of arguments_`:: Creates a communication path. As this is run via
`drbdadm proxy-up` the long list of arguments is omitted here.

`del connection  _<name>_`:: Removes a communication path.

`set memlimit _<name>_ _<memlimit-in-bytes>_`:: Sets the memory limit for a connection. This command
understands the usual units `k`, `M`, and `G`. This command can only increase the memory limit. To
reduce the memory limit, change the value in the resource file and use `drbdadm adjust`. This will
remove the connection and add it again with the lower limit.

`show`:: Shows currently configured communication paths.

`show memusage`:: Shows memory usage of each connection. For example, the following commands monitors memory usage:
+
----
# watch -n 1 'drbd-proxy-ctl show memusage'
----

`show [h]subconnections`:: Shows currently established individual connections together with some
stats. With `h` outputs bytes in human readable format.

`show [h]connections`:: Shows currently configured connections and their states With `h` outputs
bytes in human readable format. When using DRBD Proxy version 4, the `Status` column will show one
of these states:
+
* _Connecting_: No communication to the remote DRBD Proxy process.
* _ProxyConnected_: The connection to the remote DRBD Proxy is established. The connections between
  the DRBD Proxy instances and DRBD are not yet established.
* _Connected_: The DRBD connection is fully established.

`print statistics`:: This prints detailed statistics for the currently active connections, in a
format that can be easily parsed. Use this for integration to your monitoring solution!
+
NOTE: Legacy DRBD Proxy v3 only accepts the commands above from UID 0 (that is, the `root` user),
with the exception of this one which can be used by any user (provided that UNIX permissions allow
access on the proxy socket at `/var/run/drbd-proxy/drbd-proxy-ctl.socket`). Refer to the init script
at `/etc/init.d/drbdproxy` about setting the permissions.

[[s-drbd-proxy-plugins]]
=== About DRBD Proxy Plugins

DRBD Proxy version 4 only provides the `zstd` plugin.
`zstd` (Zstandard) is a real-time compression algorithm, providing high compression ratios. It
offers a very wide range of compression for speed tradeoff, while being backed by a very fast
decoder. Compression rates are dependent on "level" parameter which can be arranged between 1 to
22. Over level 20, DRBD Proxy will require more memory.

Plugin configurations for `lz4` and `zlib` are aliased to appropriate `zstd` compression levels for
backward compatibility.

link:https://linbit.com/contact-us/[Contact the LINBIT team] to find the best settings for your
environment - it depends on the CPU (speed, number of threads), available memory, input and
available output bandwidth, and expected I/O spikes. Having a week of `sysstat` data already
available helps in determining the configuration, too.

[[s-drbd-proxy-3-plugins]]
==== DRBD Proxy Version 3 Plugins

DRBD Proxy version 3 provides some additional plugins which use other software compression
algorithms.

`lz4` is a very fast compression algorithm; the data typically gets compressed down by 1:2 to
1:4, half- to two-thirds of the bandwidth can be saved.

The `zlib` plugin uses the GZIP algorithm for compression; it uses a bit more CPU than `lz4`,
but gives a ratio of 1:3 to 1:5.

The `lzma` plugin uses the `liblzma2` library. It can use dictionaries of several hundred MiB;
these allow for very efficient delta-compression of repeated data, even for small changes.
`lzma` needs much more CPU and memory, but results in much better compression than `zlib` --
real-world tests with a VM sitting on top of DRBD gave ratios of 1:10 to 1:40. The `lzma` plugin
has to be enabled in your license.

[[s-drbd-proxy-bwlimit]]
=== Using a WAN-side Bandwidth Limit

You can use the Linux kernel's traffic control framework to limit bandwidth consumed by DRBD Proxy
on the WAN side.

In the following example you would need to replace the interface name, the source port and the
IP address of the peer.

----
# tc qdisc add dev eth0 root handle 1: htb default 1
# tc class add dev eth0 parent 1: classid 1:1 htb rate 1gbit
# tc class add dev eth0 parent 1:1 classid 1:10 htb rate 500kbit
# tc filter add dev eth0 parent 1: protocol ip prio 16 u32 \
        match ip sport 7000 0xffff \
        match ip dst 192.168.47.11 flowid 1:10
# tc filter add dev eth0 parent 1: protocol ip prio 16 u32 \
        match ip dport 7000 0xffff \
        match ip dst 192.168.47.11 flowid 1:10
----

You can remove this bandwidth limitation with:

----
# tc qdisc del dev eth0 root handle 1
----

WARNING: DRBD Proxy version 3 has an experimental `bwlimit` option. Do not use
it, as it might cause applications on top of DRBD to block on I/O.

[[s-drbd-proxy-troubleshoot]]
=== Troubleshooting

The logs from DRBD Proxy version 4 are collected by the systemd journal and can be viewed with
`journalctl -u drbd-proxy`.

Enabling debug mode causes DRBD Proxy to produce more detailed logs. This can be done with the
following command.

----
# drbd-proxy-ctl set loglevel debug
----

For example, if DRBD Proxy fails to connect, it will log a corresponding message. In that case, on
both nodes, verify that DRBD is running (not in _StandAlone_ mode) and that the proxy service is
running.
Also double-check your configuration.

[[s-drbd-proxy-3-troubleshoot]]
==== Troubleshooting DRBD Proxy Version 3

DRBD Proxy 3 logs events through syslog using the `LOG_DAEMON` facility. Usually you will find
DRBD Proxy events in `/var/log/daemon.log`.

Enabling debug mode in DRBD Proxy can be done with the following command.

----
# drbd-proxy-ctl -c 'set loglevel debug'
----
