[[about]]
[preface]
== Please Read This First

This guide is intended to serve users of the Distributed Replicated
Block Device version 9 (DRBD-9) as a definitive reference guide and handbook.

ifndef::de-brand[]
It is being made available to the DRBD community by
https://www.linbit.com/[LINBIT], the project's sponsor company, free of
charge and in the hope that it will be useful. The guide is
constantly being updated. We try to add information
about new DRBD features simultaneously with the corresponding DRBD
releases. An online HTML version of this guide is always available at
https://linbit.com/drbd-user-guide/drbd-guide-9_0-en/.

IMPORTANT: This guide assumes, throughout, that you are using the latest
version of DRBD and related tools. If you are using an 8.4 release of DRBD,
please use the matching version of this guide from
https://linbit.com/drbd-user-guide/users-guide-drbd-8-4/.

Please use <<s-mailing-list,the drbd-user mailing list>> to submit
comments.
endif::de-brand[]

This guide is organized as follows:

* <<p-intro>> deals with DRBD's basic functionality. It gives a short
  overview of DRBD's positioning within the Linux I/O stack, and about
  fundamental DRBD concepts. It also examines DRBD's most important
  features in detail.

ifndef::drbd-only,de-brand[]
* <<p-build-install-configure>> talks about building DRBD from
  source, installing pre-built DRBD packages, and contains an overview
  of getting DRBD running on a cluster system.
endif::[]

* <<p-work>> is about managing DRBD using resource configuration files, as
  well as common troubleshooting scenarios.

ifndef::drbd-only[]
* <<p-apps>> deals with leveraging DRBD to add storage replication and
  high availability to applications. It not only covers DRBD
  integration in the Pacemaker cluster manager, but also advanced LVM
  configurations, integration of DRBD with GFS, using OCFS2 with DRBD,
  and using the LINBIT-developed open source DRBD Reactor software as an
  easier to configure and deploy cluster resource manager.
endif::drbd-only[]

* <<p-performance>> contains pointers for getting the best performance
  out of DRBD configurations.

* <<p-learn>> dives into DRBD's internals, and also contains pointers
  to other resources which readers of this guide may find useful.

* <<p-appendices>>:
** <<ap-recent-changes>> is an overview of changes in DRBD 9.0, compared to
earlier DRBD versions.

ifndef::de-brand[]
Users interested in DRBD training or support services are invited to
contact us at sales@linbit.com or sales_us@linbit.com.
endif::de-brand[]
