[[ch-openshift]]
== LINSTOR Volumes in OpenShift

This chapter describes the usage of LINBIT SDS in
OpenShift as managed by the LINSTOR(R) Operator and with volumes provisioned using the
https://github.com/LINBIT/linstor-csi[LINSTOR CSI plugin].

_OpenShift_ is the official Red Hat developed and supported
distribution of Kubernetes. The value of OpenShift is the strong integration
of otherwise optional components, such as network ingress and monitoring, all
tied together with a Web UI to manage it all. LINSTOR Operator integrates with
these components where possible.

[[s-openshift-deploy]]
=== Deploying LINBIT SDS on OpenShift

Deploying LINBIT SDS on OpenShift is similar to deploying LINBIT SDS on other
Kubernetes clusters. As prerequisites, you need:

* Access to your OpenShift cluster through the `oc` utility.
* Your LINBIT(R) Customer Portal credentials for accessing `drbd.io`.

IMPORTANT: LINBIT's container image repository (http://drbd.io) is only available to LINBIT
customers or through LINBIT customer trial accounts.
link:https://linbit.com/contact-us/[Contact LINBIT for information on pricing or to begin a
trial]. Alternatively, you can use the LINSTOR SDS upstream project, named
link:https://github.com/piraeusdatastore/piraeus-operator[Piraeus], without being a LINBIT
customer.

First, create a new OpenShift project for LINBIT SDS which will also create a namespace for
LINBIT SDS deployment:

----
$ oc new-project linbit-sds
Now using project "linbit-sds" on server ...
----

Next, create a file named `kustomization.yaml` to customize some of the deployment's default
values:

[source,yaml]
.kustomization.yaml
----
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linbit-sds
resources:
  - https://charts.linstor.io/static/v2.1.1.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: drbdio-pull-secret
    type: kubernetes.io/dockerconfigjson
    literals:
      - .dockerconfigjson={"auths":{"drbd.io":{"username":"MY_LINBIT_USER","password":"MY_LINBIT_PASSWORD"}}} <1>
----

<1> Replace `MY_LINBIT_USER` and `MY_LINBIT_PASSWORD` with your LINBIT customer portal
credentials.

NOTE: The YAML configuration manifest above is current at the time of writing. Refer to
https://charts.linstor.io for the most up-to-date version or previous versions if needed.

You can make additional modifications to the `kustomization.yaml` file based on your
preferences and needs. Possible options are discussed in the
<<s-kubernetes-advanced-deployments,Kubernetes advanced deployment section>>.

Finally, deploy LINBIT SDS by applying the customized configuration, and wait until all pods are
ready, by entering the following commands in the same directory as your `kustomization.yaml`:

----
$ oc apply -k . && \
oc wait --for=condition=ready pod --all -n linbit-sds --timeout=5m && \
oc get pods -n linbit-sds
----

Output should eventually show that a LINSTOR controller pod is up and running.

----
NAME                                                   READY   STATUS    RESTARTS   AGE
linstor-operator-controller-manager-59586c7bb5-qlfwb   1/1     Running   0          11s
----

After deploying the LINSTOR controller pod, enter the following command to complete the
deployment of your LINBIT SDS in OpenShift cluster:

----
# oc apply -f - <<EOF
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec: {}
EOF
# oc wait pod --for=condition=Ready -n linbit-sds --timeout=5m --all
----

Output should eventually show that your LINBIT SDS cluster pods are up and running.

----
NAME                                                   READY   STATUS    RESTARTS   AGE
ha-controller-6fl6b                                    1/1     Running   0          60s
ha-controller-c955w                                    1/1     Running   0          60s
ha-controller-v4mdr                                    1/1     Running   0          60s
kube-0                                                 2/2     Running   0          56s <1>
kube-1                                                 2/2     Running   0          56s <1>
kube-2                                                 2/2     Running   0          55s <1>
linstor-controller-779bffbc59-6jjzd                    1/1     Running   0          61s
linstor-csi-controller-8cd45658f-6f9t6                 7/7     Running   0          61s
linstor-csi-node-blgk8                                 3/3     Running   0          61s
linstor-csi-node-mn8p6                                 3/3     Running   0          61s
linstor-csi-node-pncpz                                 3/3     Running   0          61s
linstor-operator-controller-manager-59586c7bb5-qlfwb   1/1     Running   0          4m2s
----

<1> These pods are the LINSTOR satellite node pods. The pod name reflects each node's hostname.

==== Using LINBIT SDS on OpenShift

The next steps are exactly the same as in Kubernetes:

* <<s-kubernetes-storage,Configuring storage pools>>
* <<s-kubernetes-basic-configuration-and-deployment,Adding a storage class to provision a PersistentVolume>>

==== Configuring LINBIT GUI Access

The LINSTOR container images come with the LINBIT GUI preinstalled. To
expose it on your cluster, configure an OpenShift Route resource:

----
$ oc create route edge --service linstor-op-cs
$ oc get route
NAME           HOST/PORT                                  PATH  SERVICES       PORT           TERMINATION  WILDCARD
linstor-op-cs  linstor-op-cs-storage.apps.oc.example.com        linstor-op-cs  linstor-op-cs  edge         None
----

The GUI is now accessible at `+https://linstor-op-cs-storage.apps.oc.example.com/ui/+`

WARNING: This might enable external access to LINBIT GUI and LINSTOR API.
Ensure that only authorized users can access it, for example, by
requiring client side TLS certificates on the route.

==== Configuring Cluster Monitoring

OpenShift includes a fully configured monitoring stack. While most of
the monitoring stack is only intended for OpenStack infrastructure, basic
monitoring for LINBIT SDS is possible.

First, ensure that monitoring of user-defined projects is enabled in OpenShift
by following the steps in
https://docs.openshift.com/container-platform/4.6/monitoring/enabling-monitoring-for-user-defined-projects.html[Red Hat documentation].

Once monitoring for user-defined projects is enabled, the LINSTOR Operator
automatically detects the presence of OpenShift's Prometheus-based monitoring
stack and configures the `ServiceMonitor` resources. The Prometheus instance
will scrape metrics for DRBD(R) and LINSTOR from all Cluster nodes.

=== Interacting with LINBIT SDS in OpenShift

The LINSTOR Controller pod includes a LINSTOR Client,
making it easy to access LINSTOR's interactive mode. For instance:

----
$ oc exec -it deployment/linstor-op-cs-controller -- linstor interactive
LINSTOR ==> ...
----

This should only be necessary for investigating problems and accessing advanced functionality.
Regular operation such as creating volumes should be achieved through the
<<s-kubernetes-basic-configuration-and-deployment,Kubernetes integration>>.
