[[ch-linstor-gateway]]
== LINSTOR Gateway for Highly Available NFS/iSCSI Storage

*LINSTOR Gateway* manages highly available iSCSI targets and NFS exports by leveraging both LINSTOR and
DRBD Reactor.

[[s-linstor-gateway-requirements]]
=== LINSTOR Gateway Requirements

LINSTOR Gateway requires an iniitialized LINSTOR cluster, DRBD Reactor, as well as NFS and/or iSCSI utilities
be installed and configured before it can be used. The following sections cover these requirements in detail.

==== LINSTOR Cluster

The LINSTOR cluster needs to be set up as a prerequisite to using LINSTOR Gateway. For more detail regarding
LINSTOR's configuration options, please refer to the
https://linbit.com/drbd-user-guide/LINSTOR-guide-1_0-en/#s-storage_pools[LINSTOR User's Guide].

For both iSCSI and NFS, a LINSTOR `storage-pool` , `resource-group` and `volume-group` for LINSTOR Gateway needs to be
created before use. The following section provides example commands for setting up the prerequisites in a three-node
LINSTOR cluster.

Create a LVM backed storage-pool on each node using the physical device `/dev/sdb`:

----
# linstor physical-storage create-device-pool
          --pool-name lvpool LVM LINSTOR1 /dev/sdb --storage-pool lvmpool
# linstor physical-storage create-device-pool
          --pool-name lvpool LVM LINSTOR2 /dev/sdb --storage-pool lvmpool
# linstor physical-storage create-device-pool
          --pool-name lvpool LVM LINSTOR3 /dev/sdb --storage-pool lvmpool
----

Create resource-groups and volume-groups backed by the storage-pool created in the previous command:

----
# linstor resource-group create iscsi_group --storage-pool lvmpool --place-count 2
# linstor resource-group create nfs_group --storage-pool lvmpool --place-count 3
----

----
# linstor volume-group create iscsi_group
# linstor volume-group create nfs_group
----

LINSTOR Gateway requires modification of the LINSTOR Satellite's configuration on each Satellite node.
Edit or create the following file using your preferred text editor:

----
# vim /etc/linstor/linstor_satellite.toml
----

Add the following content to the Satellite configuration:

----
[files]
  allowExtFiles = [
    "/etc/systemd/system",
    "/etc/systemd/system/linstor-satellite.service.d",
    "/etc/drbd-reactor.d"
  ]
----

Save the changes to the Satellite configuration and restart the satellite service on all nodes to load the changes.

----
# systemctl restart linstor-satellite
----

==== DRBD Reactor

DRBD Reactor is a daemon that will orchestrate the iSCSI, NFS or NVMe-oF resources in our cluster. It must be installed
and the service must be enabled on all nodes in the cluster.

DRBD Reactor's main function could be summarized as such:
each DRBD Reactor daemon tries to take over DRBD Reactor managed services. The daemon that wins the race prevents other
nodes from activating the services until the original winner is no longer able to. When that happens, a new winner will
take over DRBD Reactor managed services, therefore achieving
high-availability.

For details regarding DRBD Reactor's installation and configuration options, refer to the
https://github.com/LINBIT/drbd-reactor[DRBD Reactor GitHub page].

Start and enable the DRBD Reactor service on all nodes:

----
# systemctl enable --now drbd-reactor
----

In addition to this, DRBD Reactor needs to be configured to automatically reload
when its configuration changes. Run this snippet on all nodes, as described in
the https://github.com/LINBIT/drbd-reactor#automatic-reload[DRBD Reactor README]:

----
# cp examples/drbd-reactor-reload.{path,service} /etc/systemd/system/
# systemctl enable --now drbd-reactor-reload.path
----

DRBD Reactor uses Pacemaker's resource agents when integrated with LINSTOR Gateway. You also need to install resource
agents on all nodes in the cluster. This package is named `resource-agents` in both rpm and deb based distributions:

----
# yum -y install resource-agents
----

==== iSCSI and NFS Utilities

LINSTOR Gateway requires the LIO iSCSI implementation be installed on all nodes.

The `targetcli` package can be installed on rpm based systems using the following command:

----
# yum -y install targetcli
----

For NFS support in LINSTOR Gateway, nfs-server utilities need to be installed on each node.

The `nfs-utils` package can be installed on rpm based systems using the following command:

----
# yum -y install nfs-utils
----

The NFS server should not be enabled in systemd since that will conflict with DRBD Reactors ability to manage the
service. Disable the nfs-server service and check that it has been disabled using the following commands:

----
# systemctl disable nfs-server --now
# systemctl status nfs-server
----

Ensure that the output of the command above lists the service as `inactive` and `disabled`:

----
● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; disabled; ..snip..)
   Active: inactive (dead)
----

[[s-linstor-gateway-verification]]
=== Verifying Requirements are Satisfied

The last thing we can do before starting to use LINSTOR Gateway is check that we've satisfied the prerequisites outlined
in the previous sections.

==== Verifying Components are Installed

Let's check that all the required components are present. This guide assumes you already installed and
configured a LINSTOR cluster complete with storage-pools, resource-groups, and volume-groups before using
linstor-gateway.

In addition to the initialized LINSTOR cluster, the following tools need to be present on all nodes:

* linstor-client
* drbd-reactor
* targetcli
* nfs-utils (rpm) or nfs-common (deb)
* nfs-server (rpm) or nfs-kernel-server (deb)
* resource-agents

LINSTOR Gateway provides a utility to check that the prerequisite tools are present:

----
# linstor-gateway check-health
----

This command should print something similar to the output below if you installed all of the required components. If an
error is reported, you must resolve the error before proceeding.

----
[✓] LINSTOR
[✓] drbd-reactor
[✓] Resource Agents
[✓] iSCSI
[✓] NVMe-oF
[✓] NFS
----

==== Verifying LINSTOR Cluster Initialization

Verify that the LINSTOR cluster is initialized properly by comparing your outputs are similar to the outputs in the
commands below.

Ensure all your LINSTOR nodes are listed as a Satellite or Combined type, and that you have 3 (or more) to support
quorum:

----
# linstor node list
╭────────────────────────────────────────────────────────────╮
┊ Node     ┊ NodeType  ┊ Addresses                  ┊ State  ┊
╞════════════════════════════════════════════════════════════╡
┊ LINSTOR1 ┊ COMBINED  ┊ 172.16.16.111:3366 (PLAIN) ┊ Online ┊
┊ LINSTOR2 ┊ SATELLITE ┊ 172.16.16.112:3366 (PLAIN) ┊ Online ┊
┊ LINSTOR3 ┊ SATELLITE ┊ 172.16.16.113:3366 (PLAIN) ┊ Online ┊
╰────────────────────────────────────────────────────────────╯
----

Check that LINSTOR's storage-pool list includes an LVM or ZFS backed storage-pool:

----
# linstor storage-pool list
╭─────────────────────────────────────────────────────────..snip..─────────╮
┊ StoragePool          ┊ Node     ┊ Driver   ┊ PoolName ┊ ..snip.. ┊ State ┊
╞═════════════════════════════════════════════════════════..snip..═════════╡
┊ DfltDisklessStorPool ┊ LINSTOR1 ┊ DISKLESS ┊          ┊ ..snip.. ┊ Ok    ┊
┊ DfltDisklessStorPool ┊ LINSTOR2 ┊ DISKLESS ┊          ┊ ..snip.. ┊ Ok    ┊
┊ DfltDisklessStorPool ┊ LINSTOR3 ┊ DISKLESS ┊          ┊ ..snip.. ┊ Ok    ┊
┊ lvmpool              ┊ LINSTOR1 ┊ LVM      ┊ lvpool   ┊ ..snip.. ┊ Ok    ┊
┊ lvmpool              ┊ LINSTOR2 ┊ LVM      ┊ lvpool   ┊ ..snip.. ┊ Ok    ┊
┊ lvmpool              ┊ LINSTOR3 ┊ LVM      ┊ lvpool   ┊ ..snip.. ┊ Ok    ┊
╰─────────────────────────────────────────────────────────..snip..─────────╯
----

Check that you've created at least one LINSTOR resource-group that uses your storage-pool. Also verify that each
resource-group has a corresponding volume-group:

----
# linstor resource-group list
╭────────────────────────────────────────────────────────────────╮
┊ ResourceGroup ┊ SelectFilter            ┊ VlmNrs ┊ Description ┊
╞════════════════════════════════════════════════════════════════╡
┊ DfltRscGrp    ┊ PlaceCount: 2           ┊        ┊             ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ iscsi_group   ┊ PlaceCount: 2           ┊ 0      ┊             ┊
┊               ┊ StoragePool(s): lvmpool ┊        ┊             ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ nfs_group     ┊ PlaceCount: 3           ┊ 0      ┊             ┊
┊               ┊ StoragePool(s): lvmpool ┊        ┊             ┊
╰────────────────────────────────────────────────────────────────╯
# linstor volume-group list iscsi_group
╭──────────────────╮
┊ VolumeNr ┊ Flags ┊
╞══════════════════╡
┊ 0        ┊       ┊
╰──────────────────╯
# linstor volume-group list nfs_group
╭──────────────────╮
┊ VolumeNr ┊ Flags ┊
╞══════════════════╡
┊ 0        ┊       ┊
╰──────────────────╯
----

[[s-linstor-gateway-create-iscsi]]
=== Creating iSCSI Targets

Once the preparations are complete, you can start creating iSCSI luns. The `linstor-gateway` command line utility will
be used to manage all iSCSI related actions. 

TIP: Use `linstor-gateway iscsi help` for detailed information regarding the `iscsi` subcommand.

The following command will create a new DRBD resource in the LINSTOR cluster with the specified name and resource-group.
This command also creates the DRBD Reactor configuration files to enable high availability of the iSCSI target.

----
# linstor-gateway iscsi create iqn.2019-08.com.linbit:example 192.168.122.181/24 1G \
                        --username=foo --password=bar --resource-group=iscsi_group
----

After running the command above, you will have a 1GiB iSCSI target with CHAP authentication enabled using the username and
password provided. It will be discoverable on the IP address provided in the command. The target will be backed by a
DRBD device managed by LINSTOR. The DRBD resource was created by LINSTOR in the `iscsi_group` resource-group. The DRBD
Reactor configuration files created by the above command can be found in `/etc/drbd-reactor.d/`.

You can list LINSTOR Gateway created iSCSI resources using the `linstor-gateway iscsi list` command:

----
# linstor-gateway iscsi list
+--------------------------------+--------------------+---------------+-----+---------------+
|              IQN               |     Service IP     | Service state | LUN | LINSTOR state |
+--------------------------------+--------------------+---------------+-----+---------------+
| iqn.2019-08.com.linbit:example | 192.168.122.181/24 | Started       |   1 | OK            |
+--------------------------------+--------------------+---------------+-----+---------------+
----

TIP: You can check the DRBD Reactor status using the `drbd-reactorctl status` command.

[[s-linstor-gateway-delete-iscsi]]
=== Deleting iSCSI Targets

The following command will delete the iSCSI target from DRBD Reactor as well as the LINSTOR cluster:

----
# linstor-gateway delete -i iqn.2021-04.com.linbit:lun4 -l 4
----

[[s-linstor-gateway-create-nfs]]
=== Creating NFS Exports

Before creating a NFS export you need to tell LINSTOR which filesystem the DRBD resource should be formatted with.
This is done by setting the `FileSystem/Type` property on the resource-group created for NFS exports. Use
the following LINSTOR command to do so:

----
# linstor resource-group set-property nfs_group FileSystem/Type ext4
----

TIP: You only need to set this once per resource-group, and only on the resource-group created specifically for LINSTOR
Gateway's NFS exports.

Finally, the following command will create a HA NFS export in the cluster. This single command will create a new resource within
the LINSTOR cluster using the specified name and resource-group. This command also creates the DRBD Reactor configuration
files to enable high availability of the NFS export.

----
# linstor-gateway nfs create nfstest 172.16.16.102/32 1G \
                  --allowed-ips=172.16.16.0/24 --resource-group=nfs_group
----

After running the command above, you will have a 1GiB NFS export with the specified `allowed-ips` able to mount the export
using the IP address specified as the `--service-ip`. The exports will be backed by a DRBD device managed by LINSTOR.
The DRBD resource was created by LINSTOR in the `nfs_group` resource-group. The DRBD Reactor configuration files created
by the above command can be found in `/etc/drbd-reactor.d/`.

You can list LINSTOR Gateway created NFS resources using the `linstor-gateway nfs list` command:

----
# LINSTOR-gateway nfs list
+----------+------------------+---------------+------------------------------+---------------+
| Resource |    Service IP    | Service state |          NFS export          | LINSTOR state |
+----------+------------------+---------------+------------------------------+---------------+
| nfstest  | 172.16.16.102/32 | Started       | /srv/gateway-exports/nfstest | OK            |
+----------+------------------+---------------+------------------------------+---------------+
----

TIP: You can check the DRBD Reactor status using the `drbd-reactorctl status` command.

[[s-linstor-gateway-delete-nfs]]
=== Deleting NFS Exports

The following command will delete the NFS export from DRBD Reactor as well as the LINSTOR cluster:

----
# linstor-gateway nfs delete -r nfstest
----
