[[ch-webui]]
[[ch-linstor-gui]]
== LINBIT GUI

The LINBIT GUI is an open source graphical alternative to the LINSTOR(R) CLI client.
By using the LINBIT GUI, you can adminster a LINSTOR cluster through the convenience of a graphical management console accessed through a web browser.

=== Prerequisites

To install and use the LINBIT GUI, you will need to have:

* Access to LINBIT customer or public repositories, or else you will need to build the LINBIT GUI from source by using the project's link:https://github.com/LINBIT/linstor-gui[open source codebase]
* An up and running LINSTOR controller node

=== Installing the LINBIT GUI by using a package manager

Install the `linstor-gui` package on the the LINSTOR controller node in your cluster and restart the `linstor-controller` service.
If you have made the LINSTOR controller service highly available in your cluster, also install the `linstor-gui` package on other nodes that can potentially run the service.

To install the LINBIT GUI on RPM-based distributions, enter the command:

[source,bash]
----
dnf install -y linstor-gui
----

To install the LINBIT GUI on DEB-based distributions, enter the command:

[source,bash]
----
apt install -y linstor-gui
----

With LINSTOR in Kubernetes deployments, the LINBIT GUI is a built-in feature since `linstor-controller` v1.15.0.

=== Using the LINBIT GUI to administer a LINSTOR cluster

You can access the LINBIT GUI by opening an HTTP connection with the active LINSTOR controller node via TCP port 3370.
For example, if your LINSTOR controller's IP address is 192.168.222.250, you would enter `http://192.168.222.250:3370` into your web browser's address bar to access the LINBIT GUI.

