
[[about]]
[preface]
= Please read this first

This guide is intended to serve users of the software-defined storage (SDS) solution
LINSTOR(R) as a definitive reference guide and handbook.

/////
It is being made available to the DRBD community by
https://www.linbit.com/[LINBIT], the project's sponsor company, free of
charge and in the hope that it will be useful. The guide is
constantly being updated.  We try to add information
about new DRBD features simultaneously with the corresponding DRBD
releases. An on-line HTML version of this guide is always available at
https://linbit.com/drbd-user-guide/drbd-guide-9_0-en/.
/////

IMPORTANT: This guide assumes, throughout, that you are using the latest
version of LINSTOR and related tools.

This guide is organized as follows:

* <<s-linstor-introduction>> is a foundational overview of LINSTOR and provides explanations
for LINSTOR concepts and terms.

* <<s-administrative-tasks-setup>> deals with LINSTOR's basic functionality and gives you insight into using common administrative tasks. You can also use this chapter as a step-by-step instruction guide to deploy LINSTOR with a basic, minimal setup.

* <<s-more-about-linstor>> shows a variety of advanced and important LINSTOR tasks and
configurations, so that you can use LINSTOR in more complex ways.

* <<p-webui,Using the LINBIT GUI for LINSTOR Administration>> deals with the graphical client approach to
managing LINSTOR clusters.

* <<p-linstor-integrations,LINSTOR Integrations>> has chapters that deal with how to
implement a LINSTOR based storage solution with various platforms and technologies, such as
<<ch-kubernetes,Kubernetes>>, <<ch-proxmox-linstor,Proxmox VE>>,
<<ch-opennebula-linstor,OpenNebula>>, <<ch-docker-linstor,Docker>>,
<<ch-openstack-linstor,OpenStack>>, and others, by using the LINSTOR API.

