
[[about]]
[preface]
= Please Read This First

This guide is intended to serve users of the software-defined storage (SDS) solution
LINSTOR(R) as a definitive reference guide and handbook.

/////
It is being made available to the DRBD community by
https://www.linbit.com/[LINBIT], the project's sponsor company, free of
charge and in the hope that it will be useful. The guide is
constantly being updated.  We try to add information
about new DRBD features simultaneously with the corresponding DRBD
releases. An on-line HTML version of this guide is always available at
https://linbit.com/drbd-user-guide/drbd-guide-9_0-en/.
/////


IMPORTANT: This guide assumes, throughout, that you are using the latest
version of LINSTOR and related tools.


This guide is organized as follows:

* <<s-administrative-tasks-setup>> deals with LINSTOR's basic functionality and gives you insight into using common administrative tasks. You can also use this chapter as a step-by-step instruction guide to deploy LINSTOR with a basic, minimal setup.

* In <<s-more-about-linstor>>, a variety of advanced and important LINSTOR tasks as well as configurations are shown, so that you can configure LINSTOR more complex ways.

* The chapters <<ch-kubernetes>>, <<ch-proxmox-linstor>>, <<ch-opennebula-linstor>>, <<ch-openstack-linstor>>, <<ch-docker-linstor>> illustrate how to implement a LINSTOR based storage solution with Kubernetes, Proxmox, OpenNebula, OpenStack, and Docker by using LINSTOR's API.


