[[ch-webui]]
[[ch-linstor-gui]]
== LINBIT GUI

LINBIT GUI is a LINSTOR(R) client alternative, currently in Technology
Preview phase. This component is proprietary and users need to have access to LINBIT(R) customer-only
repositories to be able to use it.

=== Prerequisites

* Access to LINBIT's customer repositories.
* Running and working LINSTOR controller instance.

=== Installing the LINBIT GUI

Install LINSTOR GUI package on the same node as the LINSTOR controller and restart the `linstor-controller` service.

On `yum/dnf` based distributions you can install the software by entering the command:

[source,bash]
----
yum install linstor-gui
----

On `apt` based distributions you install the software by entering the command:

[source,bash]
----
apt install linstor-gui
----

On Kubernetes, LINBIT GUI is a built-in feature since `linstor-controller` v1.15.0.

=== Using the LINBIT GUI to Administer a LINSTOR Cluster

You can access the LINBIT GUI by opening an HTTP connection with the active LINSTOR
controller node via TCP port 3370. For example, if your LINSTOR controller's IP address is
192.168.222.250, you would enter `http://192.168.222.250:3370` into your web browser's address
bar to use the LINBIT GUI.
