//=== The Software Stack

The section discusses the underlying software solutions LINSTOR Gateway builds on.

==== DRBD

In order for LINSTOR Gateway to be able to export highly available storage, it must be able to create said highly available storage in the first place.

To do this, it relies on the bottom-most part of the LINBIT software stack: https://github.com/LINBIT/drbd[DRBD], a "tried and true" solution for data replication and high availability clusters.

If you are not yet familiar with DRBD and want to learn more, you can refer to the
https://linbit.com/drbd-user-guide/drbd-guide-9_0-en/[_DRBD 9 User Guide_].
A deep understanding of DRBD is not required to use LINSTOR Gateway effectively, but it helps – especially when troubleshooting should any issues arise.

For a shortened – but also massively oversimplified – explanation, you can think of DRBD as a sort of "software RAID-1 over the network".

==== LINSTOR

Highly available storage via DRBD is great, but it can be difficult to manage and manipulate resources at scale.
To handle this – and many other orchestration tasks –
https://github.com/LINBIT/linstor-server[LINSTOR] was created.

As the name might imply, LINSTOR Gateway heavily relies on LINSTOR to create the DRBD resources that can later be exported as highly available storage.

Knowledge and experience with handling LINSTOR clusters helps immensely with using and understanding LINSTOR Gateway, as most of the required administration tasks are carried out within LINSTOR.

==== DRBD Reactor

The piece of software that enables LINSTOR Gateway to actually export the LINSTOR resources it created as highly available storage is
https://github.com/LINBIT/drbd-reactor[DRBD Reactor], more specifically its promoter plugin.

DRBD Reactor – again, as the name implies – _reacts_ to DRBD events.
DRBD already includes sophisticated state management mechanisms to ensure that only one node in the cluster has write access to a resource at a time.
In the promoter plugin, we use this to our advantage to make sure that a particular service is always started on the same node that is allowed to write to the resource.

This might remind you of other cluster managers, such as
https://clusterlabs.org/pacemaker/[Pacemaker].
In fact, DRBD Reactor was inspired by such cluster managers and its goals and features overlap with some of Pacemaker’s.

However, administrators often face difficulties when implementing highly available clusters using these cluster managers in combination with DRBD, due to the sheer complexity of such a system.

This is why the DRBD Reactor promoter plugin was intentionally designed as a very simple cluster manager that is useful with minimal configuration needed for existing DRBD deployments.

==== Resource Agents

The DRBD Reactor promoter plugin needs a service to keep highly available.
Fortunately, it was built with cross-compatibility to Pacemaker in mind.
Because of this, Pacemaker's https://github.com/ClusterLabs/resource-agents[OCF Resource Agents] are supported in DRBD Reactor.

This is very convenient because it allows LINSTOR Gateway to re-use existing code that makes services such as iSCSI targets and NFS exports highly available.

==== Putting It All Together

Finally, this is where LINSTOR Gateway comes in.

In a nutshell, LINSTOR Gateway actually only does two things:

1. Creates a LINSTOR resource for highly available, replicated storage.
2. Generates a DRBD Reactor configuration file that starts the highly available service we want to provide (for example, an iSCSI target).

Of course, there are still challenges associated with "doing it right" for every possible use-case and context that highly available storage might be used in.

This is why LINSTOR Gateway aims to automate away as much of the setup and maintenance work as possible, so that the administrator can focus on using their highly available storage effectively.
