//=== Servers, clients, and agents

Generally speaking, within a LINSTOR Gateway cluster, there are three different kinds of roles that a node can take.
It can either be used as 1. a
_server_, 2. a _client_, or 3. an _agent_.

It is also possible for a node to take more than one role. Any combination of the three roles is possible.
This section outlines what sets these roles apart, both conceptually and in terms of the software components used.

==== Server

image::images/linstorgw-gateway-server.svg[LINSTOR Gateway Server diagram]

The server role is LINSTOR Gateway's main mode of operation.
The main task of the server component is *to communicate with the LINSTOR controller*.

NOTE: It is important to understand that the LINSTOR Gateway server *does not store any state information itself*.
It does not matter on which machine it runs, provided that it can reach the LINSTOR controller.

==== Client

image::images/linstorgw-gateway-client.svg[LINSTOR Gateway client]

This is any piece of software that interacts with LINSTOR Gateway via LINSTOR Gateway's REST API.
In most cases, this will be the command line client that is included with LINSTOR Gateway.

It is the interface between LINSTOR Gateway and the user.

Even if there are multiple LINSTOR Gateway servers in a cluster, the client only ever talks to one of them.

==== Agent

The _agent_ is a more abstract role for a node, in the sense that it does not necessarily run any part of the LINSTOR Gateway software itself.
Instead, it contains the software components that LINSTOR Gateway uses to provide its services, for example:

* `targetcli` for iSCSI targets
* `nfs-server` to provide NFS exports
* `nvmetcli` to create NVMe-oF targets

To be a proper part of the cluster, an agent node also requires the essential components of a LINBIT SDS software stack, such as:

* The DRBD kernel module
* A LINSTOR cluster node that runs the `linstor-satellite` service
* DRBD Reactor, to be able to run highly available resources

The *health check* integrated into the LINSTOR Gateway Client binary can be used to identify which components are still missing or misconfigured on a given node.
