[[ch-linstor-gateway]]
== Exporting Highly Available Storage using LINSTOR Gateway

*LINSTOR Gateway* manages highly available iSCSI targets and NFS exports by leveraging on LINSTOR and
DRBD Reactor. Setting up LINSTOR including storage pools and resource groups is neccessary to use this tool.

[[s-linstor-gateway-requirements]]
=== Requirements

==== LINSTOR

A LINSTOR cluster is required to operate LINSTOR Gateway. The LINSTOR
cluster needs to be formed upfront. For more details, please refer
to the https://linbit.com/drbd-user-guide/LINSTOR-guide-1_0-en/#s-storage_pools[LINSTOR user guide]

For both iSCSI and NFS, `storage pool` , `resource group` and a `volume group` for LINSTOR Gateway needs to be
present. Lets do it;

Creating the storage pool in 3 nodes using the phsical device `/dev/sdb`;

-----------------
linstor physical-storage create-device-pool --pool-name lvpool LVM LINSTOR1 /dev/sdb --storage-pool lvmpool
linstor physical-storage create-device-pool --pool-name lvpool LVM LINSTOR2 /padev/sdb --storage-pool lvmpool
linstor physical-storage create-device-pool --pool-name lvpool LVM LINSTOR3 /dev/sdb --storage-pool lvmpool
-----------------

We also need to create resource groups and volume groups;

-----------------
linstor rg c iscsi_group --storage-pool lvmpool --place-count 2
linstor rg c nfs_group --storage-pool lvmpool --place-count 3
-----------------

-----------------
linstor vg c iscsi_group
linstor vg c nfs_group
-----------------

For a more detailed explanation of the storage pool, resource group and volume group creation, check the
https://linbit.com/drbd-user-guide/LINSTOR-guide-1_0-en/#s-storage_pools[LINSTOR user guide]

LINSTOR Gateway needs small adjustment in the LINSTOR cluster after its created. You need to create a 
file in all nodes and add the following content in to it.

-----------------
nano /etc/linstor/linstor_satellite.toml
-----------------

add the content

-----------------
 [files]
        allowExtFiles = ["/etc/systemd/system", "/etc/systemd/system/linstor-satellite.d", "/etc/drbd-reactor.d"]
-----------------

After adding the content in to the /etc/linstor/linstor_satellite.toml file, you need to restart the 
satellite service on all nodes to make it effective. 

-----------------
systemctl restart linstor-satellite
-----------------


==== DRBD Reactor

The DRBD Reactor is a daemon that will do all the orchestration for iSCSI, NFS or NVMe-oF. It must be installed on all 
servers and the service must be activated. The working logic is briefly as follows; each DRBD Reactor daemon tries to 
take over services. The daemon that wins the race prevents other nodes from activating the service. 

For installation and configuration of DRBD Reactor, you can check the following link; https://github.com/LINBIT/drbd-reactor[DRBD Reactor]

Note: After installing DRBD Reactor and activating as a service in to the system, LINSTOR Gateway will take care all of the configuration.
So you dont need to edit any file or service for the DRBD Reactor. 

-----------------
systemctl enable --now drbd-reactor
-----------------

DRBD Reactor uses Pacemaker's resource agents. You also need to install resource agents in to the server with the following command;

-----------------
yum -y install resource-agents
-----------------

==== iSCSI & NFS

LINSTOR Gateway requires an iSCSI implementation to be installed. Using `targetcli` is recommended.

For iSCSI, please install targetcli.

-----------------
yum install targetcli
-----------------

For NFS, nfs-server needs to be present in the server. NFS server should not be enabled by systemctl 
because it conflicts with the resource agent if its started. Check the status of nfs-server with;

-----------------
systemctl status nfs-server
-----------------

output should be like;

-----------------
● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
-----------------

[[s-linstor-gateway-preparation]]
=== Preparation
First, let's check that all the components are available. This guide assumes you already installed and
configured a LINSTOR cluster. Volume Group, Storage Pool and Resource Group should be defined before using
linstor-gateway

Tools need to be present in server;

* linstor-client (managing the LINSTOR cluster)
* drbd-reactor (in all servers)
* targetcli (for iSCSI)
* nfs-utils, nfs-server (for nfs)
* pacemaker resource agents

There is a good option in LINSTOR Gateway for checking all the tools and settings before you go. 

-----------------
linstor-gateway check-health 
-----------------

This command should print something like this if you installed all of the components. In case of any error, please check the error and fix it. 
-----------------
[✓] LINSTOR
[✓] drbd-reactor
[✓] Resource Agents
[✓] iSCSI
[✓] NVMe-oF
[✓] NFS
-----------------

[[s-linstor-gateway-checking]]

=== Checking the Cluster

Check the LINSTOR cluster status with;

-----------------
[root@LINSTOR1 ~]# linstor n l
╭────────────────────────────────────────────────────────────╮
┊ Node     ┊ NodeType  ┊ Addresses                  ┊ State  ┊
╞════════════════════════════════════════════════════════════╡
┊ LINSTOR1 ┊ COMBINED  ┊ 172.16.16.111:3366 (PLAIN) ┊ Online ┊
┊ LINSTOR2 ┊ SATELLITE ┊ 172.16.16.112:3366 (PLAIN) ┊ Online ┊
┊ LINSTOR3 ┊ SATELLITE ┊ 172.16.16.113:3366 (PLAIN) ┊ Online ┊
╰────────────────────────────────────────────────────────────╯
-----------------

Check the LINSTOR storage pool list with;

-----------------
root@LINSTOR1 ~]# linstor sp l
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ StoragePool          ┊ Node     ┊ Driver   ┊ PoolName ┊ FreeCapacity ┊ TotalCapacity ┊ CanSnapshots ┊ State ┊
╞═════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ DfltDisklessStorPool ┊ LINSTOR1 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊
┊ DfltDisklessStorPool ┊ LINSTOR2 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊
┊ DfltDisklessStorPool ┊ LINSTOR3 ┊ DISKLESS ┊          ┊              ┊               ┊ False        ┊ Ok    ┊
┊ lvmpool              ┊ LINSTOR1 ┊ LVM      ┊ lvpool   ┊    10.00 GiB ┊     10.00 GiB ┊ False        ┊ Ok    ┊
┊ lvmpool              ┊ LINSTOR2 ┊ LVM      ┊ lvpool   ┊    10.00 GiB ┊     10.00 GiB ┊ False        ┊ Ok    ┊
┊ lvmpool              ┊ LINSTOR3 ┊ LVM      ┊ lvpool   ┊    10.00 GiB ┊     10.00 GiB ┊ False        ┊ Ok    ┊
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
-----------------

LINSTOR resource group list (please do not forget to create volume group for the resource group with:
`linstor vg c iscsi_group`)

-----------------
[root@LINSTOR1 ~]# linstor rg l
╭────────────────────────────────────────────────────────────────╮
┊ ResourceGroup ┊ SelectFilter            ┊ VlmNrs ┊ Description ┊
╞════════════════════════════════════════════════════════════════╡
┊ DfltRscGrp    ┊ PlaceCount: 2           ┊        ┊             ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ iscsi_group   ┊ PlaceCount: 2           ┊ 0      ┊             ┊
┊               ┊ StoragePool(s): lvmpool ┊        ┊             ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ nfs_group     ┊ PlaceCount: 3           ┊ 0      ┊             ┊
┊               ┊ StoragePool(s): lvmpool ┊        ┊             ┊
╰────────────────────────────────────────────────────────────────╯

-----------------


[[s-linstor-gateway-setup-iscsi]]
=== Setting up iSCSI target


Now, everything looks good, let's start creating our first iSCSI lun. "linstor-gateway" command will be used for all
iSCSI related actions. Please check "linstor-gateway iscsi help" for detailed usage. At first it creates a new
resource within the LINSTOR system under the specified name and using the specified resource group. After that
it creates DRBD Reactor configuration files for high availability of the service.

------------------------
linstor-gateway iscsi create --iqn=iqn.2019-08.com.linbit:example --ip=192.168.122.181/24 --username=foo --lun=1 --password=bar --resource-group=iscsi_group --size=1G
------------------------

This command will create a 1G iSCSI disk with the provided username and password in the resource group defined
`iscsi_group` DRBD and DRBD Reactor configuration files will be automatically created by linstor-gateway. You can check the
DRBD Reactor status with "drbd-reactorctl status" command.

------------------------
[root@LINSTOR1 ~]# linstor-gateway iscsi list
+--------------------------------+--------------------+---------------+-----+---------------+
|              IQN               |     Service IP     | Service state | LUN | LINSTOR state |
+--------------------------------+--------------------+---------------+-----+---------------+
| iqn.2019-08.com.linbit:example | 192.168.122.181/24 | Started       |   1 | OK            |
| iqn.2019-08.com.linbit:test1   | 192.168.122.182/24 | Started       |   2 | OK            |
| iqn.2019-08.com.linbit:test2   | 192.168.122.183/24 | Started       |   3 | OK            |
| iqn.2019-08.com.linbit:test3   | 172.16.16.123/24   | Started       |   4 | OK            |
+--------------------------------+--------------------+---------------+-----+---------------+
------------------------

[[s-linstor-gateway-delete-iscsi]]
=== Deleting iSCSI target

The following command will delete the iSCSI target from DRBD Reactor as well as the LINSTOR cluster;

------------------------
linstor-gateway delete -i iqn.2021-04.com.linbit:lun4 -l 4
------------------------

[[s-linstor-gateway-setup-nfs]]
=== Setting up NFS export

Before creating the NFS exports you need to tell LINSTOR that filesystem will be used for NFS exports will be
EXT4. in order to do that, we'll apply a property to the resource group of NFS resources simply by typing;

------------------------
linstor rg set-property nfs_group FileSystem/Type ext4
------------------------

The following command will create a NFS export in the cluster. At first it creates a new resource within the
LINSTOR system under the specified name and using the specified resource group. After that it creates necessary 
resources in order within DRBD Reactor. 

------------------------
linstor-gateway nfs create --resource=nfstest --service-ip=172.16.16.102/32 --allowed-ips=172.16.16.0/24 --resource-group=nfs_group --size=1G
------------------------

You can simply list the nfs exports with the command below;

------------------------
[root@LINSTOR1 ~]# LINSTOR-gateway nfs list
+----------+------------------+---------------+------------------------------+---------------+
| Resource |    Service IP    | Service state |          NFS export          | LINSTOR state |
+----------+------------------+---------------+------------------------------+---------------+
| nfstest  | 172.16.16.102/32 | Started       | /srv/gateway-exports/nfstest | OK            |
+----------+------------------+---------------+------------------------------+---------------+
------------------------

[[s-linstor-gateway-delete-nfs]]
=== Deleting NFS Export

The following command will delete the nfs export from DRBD Reactor as well as the LINSTOR cluster;

------------------------
[root@LINSTOR1 ~]# linstor-gateway nfs delete -r nfstest
------------------------
