//=== Choosing the right transport

LINSTOR Gateway supports different storage transport protocols.
This section briefly explains the differences between these options and when you might use one over the other.

For more detailed information about a specific transport, refer to its documentation.

==== iSCSI Targets

https://datatracker.ietf.org/doc/html/rfc7143[iSCSI] is a transport protocol that allows SCSI traffic to be sent via TCP.
The standard has seen wide use since its inception in the early 2000s, so it has often been viewed as the "default choice" for network-attached storage.

LINSTOR Gateway uses an iSCSI target implementation that is included in the Linux kernel, LIO.

==== NVMe-oF Targets

https://nvmexpress.org/developers/nvme-of-specification/[NVMe over Fabrics] is a much newer standard relative to iSCSI.
It allows routing NVMe traffic over several different physical transports, such as RDMA, Ethernet (TCP/IP) or Fibre Channel.

Linux kernel support for NVMe over Fabrics targets is -- generally speaking -- more actively maintained than support for iSCSI target implementations.
Using NVMe-oF might lead to throughput improvements in a storage cluster, especially when using modern high-performance hardware.

LINSTOR Gateway uses the NVMe target implementation bundled with the Linux kernel.

==== NFS Exports

The https://en.wikipedia.org/wiki/Network_File_System[Network File System (NFS)] serves a different purpose than iSCSI and NVMe-oF.

Rather than transmitting block-level data over the network, NFS is a distributed file system.
NFS exports are often used to share directories across a network.
One common use case would be providing images of operating system installation media to virtualization hosts.

NOTE: LINSTOR Gateway currently only supports a relatively limited mode of NFS operation, without user management capabilities.
All files on the share are readable and writable by any user.

LINSTOR Gateway uses the NFS server implementation that is included with Linux.
