[[ch-more-info]]
== Getting more information

ifndef::de-brand[]
[[s-commercial-support]]
=== Commercial DRBD support

Commercial DRBD support, consultancy, and training services are
available from the project's sponsor company,
http://www.linbit.com/[LINBIT].
endif::de-brand[]

[[s-mailing-list]]
=== Public mailing list

The public mailing list for general usage questions regarding DRBD is
drbd-user@lists.linbit.com. This is a subscribers-only mailing list,
you may subscribe at https://lists.linbit.com/listinfo/drbd-user/. A complete
list archive is available at
https://lists.linbit.com/pipermail/drbd-user/.

ifndef::de-brand[]
[[s-twitter-account]]
=== Official Twitter account

http://www.linbit.com/[LINBIT] maintains an official http://twitter.com/linbit[twitter account].

If you tweet about DRBD, please include the `#drbd` hashtag.
endif::de-brand[]

[[s-publications]]
=== Publications

DRBD's authors have written and published a number of papers on DRBD
in general, or a specific aspect of DRBD. Here is a short selection:

[bibliography]
- Philipp Reisner. 'DRBD 9 - What's New'. 2012. Available at
  http://www.drbd.org/fileadmin/drbd/publications/whats-new-drbd-9.pdf
	// FIXME only bad version at https://www.netways.de/fileadmin/images/Events_Trainings/Events/OSDC/2013/Slides_2013/Philipp_Reisner_Neues_in_DRBD9.pdf
	// FIXME - put fixed version there
- Lars Ellenberg. 'DRBD v8.0.x and beyond'. 2007. Available at
  http://drbd.linbit.com/fileadmin/drbd/publications/drbd8.linux-conf.eu.2007.pdf
- Philipp Reisner. 'DRBD v8 - Replicated Storage with Shared Disk
  Semantics'. 2007. Available at
  http://drbd.linbit.com/fileadmin/drbd/publications/drbd8_orig.pdf
  FIXME sagt 2005?
- Philipp Reisner. 'Rapid resynchronization for replicated
  storage'. 2006. Available at
  http://drbd.linbit.com/fileadmin/drbd/publications/drbd-activity-logging_v6.pdf.

You can find many more on http://drbd.linbit.com/home/publications/.
