[[ch-opennebula]]
== DRBD Volumes in OpenNebula

indexterm:[OpenNebula]This chapter describes DRBD in OpenNebula via the usage
of the https://github.com/OpenNebula/addon-linstor[LINSTOR storage driver
addon].

Detailed installation and configuration instructions and be found in the
https://github.com/OpenNebula/addon-linstor/blob/master/README.md[README.md]
file of the driver's source.

[[s-opennebula-overview]]
=== OpenNebula Overview

http://opennebula.org/[OpenNebula] is a flexible and open source cloud
management platform which allows its functionality to be extended via the use
of addons.

The LINSTOR addon allows the deployment of virtual machines with highly
available images backed by DRBD and attached across the network via DRBD's
own transport protocol.

[[s-opennebula-install]]
=== OpenNebula Installation

Installation of the LINSTOR storage addon for OpenNebula requires a working
OpenNebula cluster as well as a working LINSTOR cluster.

OpenNebula provides documentation of its
http://docs.opennebula.org/5.6/deployment/index.html[design and installation],
which should be consulted when considering the creation of a new OpenNebula
cluster.

A DRBD cluster with LINSTOR can be installed and configured by following the
instructions in this guide, see <<s-linstor-init-cluster>>.

The OpenNebula and DRBD clusters can be somewhat independent of one another
with the following exception: OpenNebula's Front-End and Host nodes must be
included in both clusters.

Host nodes do not need a local LINSTOR storage pools, as virtual machine
images are attached to them across the network footnote:[If a host is also a
storage node, it will use a local copy of an image if that is available].

Instructions for installing and configuring the LINSTOR addon for OpenNebula
can be found in the `README.md` file of the addon, which will be rendered by
visiting the https://github.com/OpenNebula/addon-linstor[GitHub page] for the
driver.

[[s-opennebula-deployment-options]]
=== Deployment Options

Resources may be automatically placed or assigned to specific nodes.
Generally, automatic assignment is preferred as LINSTOR will automatically
scale as more nodes are added to the cluster, provided they have the storage
pool that matches the one that the driver is configured to use.

The driver also allows for the selection of storage pools on a per-datastore
basis. If no storage pool is selected, the default storage pool will be used.


[[s-opennebula-live-migration]]
=== Live Migration

Live migration is supported even with the use of the ssh system datastore, as
well as the nfs shared system datastore.

[[s-opennebula-free-space]]
=== Free Space Reporting

Free space is calculated differently depending on whether resources are
deployed automatically or on a per node basis.

For datastores which place per node, free space is reported based on
the most restrictive storage pools from all nodes where resources are being
deployed. For example, the capacity of the node with the smallest amount of
total storage space is used to determine the total size of the datastore and
the node with the least free space is used to determine the remaining space in
the datastore.

For a datastore which uses automatic placement, size and remaining space are
determined based on the aggregate storage pool used by the datastore as
reported by LINSTOR.
