[[ch-proxmox]]
== DRBD Volumes in Proxmox VE

indexterm:[Proxmox]This chapter describes DRBD in Proxmox VE via
the http://git.linbit.com/drbdmanage-proxmox.git[DRBD Manage Proxmox Plugin].

[[s-proxmox-overview]]
=== Proxmox VE Overview

http://www.proxmox.com/en/[Proxmox VE] is an easy to use, complete server
virtualization environment with KVM, Linux Containers and HA.

'drbdmanage-proxmox' is a Perl plugin for Proxmox that, in combination with DRBD Manage, allows to replicate VM
//(LVM volumes on DRBD)
disks  on several Proxmox VE nodes. This allows to live-migrate
active VMs within a few seconds and with no downtime without needing a central SAN, as the data is already
replicated to multiple nodes.

[[s-proxmox-install]]
=== Proxmox Plugin Installation

LINBIT provides a dedicated public repository for Proxmox VE users. This repository not only contains the
Proxmox plugin, but the whole DRBD SDS stack including a customized version of DRBD Manage, DRBD SDS kernel
module and user space utilities, and of course the Proxmox Perl plugin itself.

The DRBD9 kernel module gets installed as a `dkms` package (i.e., `drbd-dkms`), therefore you want to install
`pve-headers` before you set up/install software from LINBIT's repositories. Following that order ensures that
the kernel module is built for your kernel. If you do not follow the latest Proxmox kernel, you have to
install kernel headers matching your current kernel (e.g., `pve-headers-$(uname -r)`). If you did not follow
that advice and you need to rebuild the dkms package against your current kernel (headers have to be
installed), you can issue `apt-get install --reinstall drbd-dkms`.

LINBIT's repository can be enabled as follows, where "$PVERS" should be set to your Proxmox VE *major version*
(e.g., "5", not "5.2"):

----------------------------
# wget -O- https://packages.linbit.com/package-signing-pubkey.asc | apt-key add -
# PVERS=5 && echo "deb http://packages.linbit.com/proxmox/ proxmox-$PVERS drbd-9.0" > \
	/etc/apt/sources.list.d/linbit.list
# apt-get purge drbdmanage
# apt-get update && apt-get install drbdmanage-proxmox
----------------------------

If you are already (or have been) using Proxmox's version of DRBD Manage, you can simply enable the repository and
install `drbdmanage-proxmox`; you don't have to change the existing configuration.

[[s-proxmox-configuration]]
=== Proxmox Plugin Configuration

The first step is to set up a static IP address for DRBD traffic. As Proxmox is Debian GNU/Linux based, this is
configured via `/etc/network/interfaces`.

The second step is to configure DRBD Manage as described in <<s-dm-init-cluster>>.

The third and last step is to provide a configuration for Proxmox itself. This is done by adding an entry to
`/etc/pve/storage.cfg` with the following content, assuming a three node cluster in this example:

----------------------------
drbd: drbdstorage
   content images,rootdir
   redundancy 3
----------------------------

After that you can create VMs via Proxmox's web GUI by selecting "__drbdstorage__" as storage location.

.NOTE: DRBD supports only the **raw** disk format at the moment.

At this point you can try to live migrate the VM - as all data is available on both nodes it will take just a
few seconds. The overall process might take a bit longer if the VM is under load and if there is a lot of RAM
being dirtied all the time. But in any case, the downtime is minimal and you will see no interruption at all.
