[[ap-recent-changes]]
[appendix]
== Recent changes

This appendix is for users who upgrade from earlier DRBD versions to
DRBD 9.0. It highlights some important changes to DRBD's configuration
and behavior.

[[s-recent-changes-connections]]
=== Connections

With DRBD 9 data can be replicated across more than two nodes.

Associated with this change are

* Metadata size changes (one bitmap per peer)

* `/proc/drbd` now only gives minimal information, see
    <<s-drbdadm-status, `drbdadm status`>>

* Resynchronization from/to <<s-multi-node,multiple peers>>

* The <<s-activity-log,activity log>> is used even when in
  <<s-resource-roles,Secondary>> role

[[s-recent-changes-performance]]
=== Increased Performance

DRBD 9 has seen noticeable performance improvements, depending on your specific
hardware it's up to two magnitudes faster (measuring number of I/O
operations/second for random writes).

//FIXME: same as 8.4?


[[s-recent-changes-volumes]]
=== Multiple Volumes in one Resource

Volumes are a new concept in DRBD 8.4. Prior to 8.4, every resource
had only one block device associated with it, thus there was a
one-to-one relationship between DRBD devices and resources. Since 8.4,
multiple volumes (each corresponding to one block device) may share a
single replication connection, which in turn corresponds to a single
resource.

This results in a few other necessary changes in behaviour:

[[s-recent-changes-volumes-udev]]
==== Changes to udev symlinks

The DRBD udev integration scripts manage symlinks pointing to
individual block device nodes. These exist in the `/dev/drbd/by-res/`
and `/dev/drbd/by-disk/` directories.

Since DRBD 8.4, a single resource may correspond to multiple
volumes, `/dev/drbd/by-res/__<resource>__` is a _directory_,
containing symlinks pointing to individual volumes:

.udev managed DRBD symlinks in DRBD 8.4
----------------------------
lrwxrwxrwx 1 root root 11 2015-08-09 19:32 /dev/drbd/by-res/home/0 -> ../../drbd0
lrwxrwxrwx 1 root root 11 2015-08-09 19:32 /dev/drbd/by-res/data/0 -> ../../drbd1
lrwxrwxrwx 1 root root 11 2015-08-09 19:33 /dev/drbd/by-res/nfs-root/0 -> ../../drbd2
lrwxrwxrwx 1 root root 11 2015-08-09 19:33 /dev/drbd/by-res/nfs-root/1 -> ../../drbd3
----------------------------

Configurations where filesystems are referred to by such a symlink must be
updated when moving to DRBD 8.4, usually by simply appending `/0` to
the symlink path. If the filesystem was referenced via `UUID=` or
`/dev/drbd__X__` in `/etc/fstab`, no change is necessary.


[[s-recent-changes-config]]
=== Changes to the configuration syntax

This section highlights changes to the configuration syntax. It
affects the DRBD configuration files in `/etc/drbd.d`, and
`/etc/drbd.conf`.

IMPORTANT: The `drbdadm` parser still accepts pre-8.4 configuration
syntax and automatically translates, internally, into the current
syntax. Unless you are planning to use new features from DRBD 9,
there is no requirement to modify your
configuration to the current syntax. It is, however, recommended that
you eventually adopt the new syntax, as the old format will no longer
be supported in DRBD 9.

[[s-recent-changes-config-booleans]]
==== Boolean configuration options

`drbd.conf` supports a variety of boolean configuration options. In
pre DRBD 8.4 syntax, these boolean options would be set as follows:

.Pre-DRBD 8.4 configuration example with boolean options
[source,drbd]
----------------------------
resource test {
	disk {
		no-md-flushes;
	}
}
----------------------------

This led to configuration issues if you wanted to set a boolean
variable in the `common` configuration section, and then override it
for individual resources:

.Pre-DRBD 8.4 configuration example with boolean options in `common` section
[source,drbd]
----------------------------
common {
	disk {
		no-md-flushes;
	}
}
resource test {
	disk {
		# No facility to enable disk flushes previously disabled in
		# "common"
	}
}
----------------------------

In DRBD 8.4, all boolean options take a value of `yes` or `no`, making
them easily configurable both from `common` and from individual
`resource` sections:

.DRBD 8.4 configuration example with boolean options in `common` section
[source,drbd]
----------------------------
common {
  md-flushes no;
}
resource test {
  disk {
    md-flushes yes;
  }
}
----------------------------


[[s-recent-changes-net]]
=== On-line changes to network communications

[[s-recent-changes-change-protocol]]
==== Changing the replication protocol

Prior to DRBD 8.4, changes to the replication protocol were impossible
while the resource was on-line and active. You would have to change
the `protocol` option in your resource configuration file, then issue
`drbdadm disconnect` and finally `drbdadm connect` on both nodes.

In DRBD 8.4, the replication protocol can be changed on the fly. You
may, for example, temporarily switch a connection to asynchronous
replication from its normal, synchronous replication mode.

.Changing replication protocol while connection is established
----------------------------
drbdadm net-options --protocol=A <resource>
----------------------------

[[s-recent-changes-drbdadm]]
=== Changes to the `drbdadm` command

[[s-recent-changes-drbdadm-passthrough-options]]
==== Changes to pass-through options

Prior to DRBD 8.4, if you wanted `drbdadm` to pass special options through to
`drbdsetup`, you had to use the arcane `--{nbsp}--<option>` syntax, as in the
following example:

.Pre-DRBD 8.4 `drbdadm` pass-through options
----------------------------
drbdadm -- --discard-my-data connect <resource>
----------------------------

Instead, `drbdadm` now accepts those pass-through options as normal options:

.DRBD 8.4 `drbdadm` pass-through options
----------------------------
drbdadm connect --discard-my-data <resource>
----------------------------

NOTE: The old syntax is still supported, but its use is strongly
discouraged. However, if you choose to use the new, more
straightforward syntax, you must specify the option
(`--discard-my-data`) _after_ the subcommand (`connect`) and _before_
the resource identifier.

[[s-recent-changes-drbdadm-force]]
==== `--force` option replaces `--overwrite-data-of-peer`

The `--overwrite-data-of-peer` option is no longer present in DRBD
8.4. It has been replaced by the simpler `--force`. Thus, to kick off
an initial resource synchronization, you no longer use the following
command:

.Pre-DRBD 8.4 initial sync `drbdadm` commands
----------------------------
drbdadm -- --overwrite-data-of-peer primary <resource>
----------------------------

Use the command below instead:

.DRBD 8.4 initial sync `drbdadm` commands
----------------------------
drbdadm primary --force <resource>
----------------------------


[[s-recent-changes-defaults]]
=== Changed default values

In DRBD 8.4, several `drbd.conf` default values have been updated to
match improvements in the Linux kernel and available server hardware.

[[s-recent-changes-defaults-al-extents]]
==== Number of concurrently active Activity Log extents (`al-extents`)

``al-extents``' previous default of 127 has changed to 1237, allowing
for better performance by reducing the amount of metadata disk write
operations. The associated extended resynchronization time after a
primary node crash, which this change introduces, is marginal given
the ubiquity of Gigabit Ethernet and higher-bandwidth replication
links.

[[s-recent-changes-defaults-use-rle]]
==== Run-length encoding (`use-rle`)

Run-length encoding (RLE) for bitmap transfers is enabled by default
in DRBD 8.4; the default for the `use-rle` option is `yes`. RLE
greatly reduces the amount of data transferred during the
<<s-quick-sync-bitmap,quick-sync bitmap>> exchange (which occurs any
time two disconnected nodes reconnect).

[[s-recent-changes-on-io-error]]
==== I/O error handling strategy (`on-io-error`)

DRBD 8.4 defaults to <<fp-io-error-detach,masking I/O errors>>, which
replaces the earlier behavior of <<fp-io-error-pass-on,passing them on>>
to upper layers in the I/O stack. This means that a DRBD volume
operating on a faulty drive automatically switches to the _Diskless_
disk state and continues to serve data from its peer node.

[[s-recent-changes-defaults-variable-rate-sync]]
==== Variable-rate synchronization

<<s-variable-rate-sync,Variable-rate synchronization>> is on by
default in DRBD 8.4. The default settings are equivalent to the
following configuration options:

.DRBD 8.4 default options for variable-rate synchronization
[source,drbd]
----------------------------
resource test {
  disk {
    c-plan-ahead 20;
    c-fill-target 50k;
    c-min-rate 250k;
  }
  ...
----------------------------

[[s-recent-changes-defaults-minor-count]]
==== Number of configurable DRBD devices (`minor-count`)

The maximum number of configurable DRBD devices (previously 255) is
1,048,576 (2^20^) in DRBD 8.4. This is more of a theoretical limit
that is unlikely to be reached in production systems.
