// vim: :set ft=asciidoc tw=70 fo-=a sw=8 ts=8 noet spell
[[ch-webui]]
== LINSTOR Web UI

LINSTOR Web UI is a LINSTOR client alternative, currently in Technology
Preview phase. This component is proprietary and users need to have access to LINBIT customer only
repositories in order to be able to use it.

=== Prerequisites
* Access to LINBIT's customer repositories.
* Running and working LINSTOR controller instance.

=== Installation
Install LINSTOR Web UI package on the same node as the LINSTOR controller and restart the `linstor-controller`
service.

On `yum/dnf` based distribution you can install the software via:

[source,bash]
----
yum install linstor-gui
----

On `apt` based distributions you install the software via:

[source,bash]
----
apt install linstor-gui
----

On Kubernetes LINSTOR Web UI is a built-in feature since linstor-controller v1.15.0.

=== Administration
Open your web browser and navigate to `http://CONTROLLER_IP:3370/ui/` (the last `/` is mandatory) to manage
your LINSTOR cluster.
